### ISSUE TITLE
Select your timezone page blank; can't continue installation

### ISSUE THREAD

**Issue by jpambrun** [Antergos/Cnchi#1026]
**Describe the bug**

The 'select your timezone' page is blank and I can't proceed forward.
Looking at the logs, it seems to correctly detect that I am in Montreal ('America/Montreal'), but this location is missing from the collection?

**To Reproduce**
1. from Montreal..
2. Try to install
3. At 'select your timezone' the pane is completely empty. The only button that works is 'back' and it is impossible to proceed with installation.

**Expected behavior**
Display a map where I can select a timezone.

**Log Files**
```
018-09-05 13:08:34 [DEBUG] location.py(272) store_values(): Selected location: English (US), United States
2018-09-05 13:08:35 [DEBUG] location.py(290) store_values(): Selected country name: United States
2018-09-05 13:08:35 [DEBUG] location.py(291) store_values(): Selected country code: us
2018-09-05 13:08:35 [DEBUG] connectionpool.py(205) _new_conn(): Starting new HTTP connection (1): build.antergos.com:80
2018-09-05 13:08:36 [DEBUG] connectionpool.py(393) _make_request(): http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 301 None
2018-09-05 13:08:36 [DEBUG] connectionpool.py(393) _make_request(): http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/share/cnchi/src/main_window.py", line 488, in on_forward_button_clicked
    self.current_page.prepare('forwards')
2018-09-05 13:08:36 [DEBUG] connectionpool.py(823) _new_conn(): Starting new HTTPS connection (1): notify.bugsnag.com:443
  File "/usr/share/cnchi/src/pages/timezone.py", line 211, in prepare
    self.set_timezone(timezone)
  File "/usr/share/cnchi/src/pages/timezone.py", line 142, in set_timezone
    res = self.tzmap.set_timezone(timezone)
  File "/usr/share/cnchi/src/misc/timezonemap.py", line 485, in set_timezone
    real_tz = self.tzdb.get_loc(time_zone)
  File "/usr/share/cnchi/src/misc/tz.py", line 309, in get_loc
    return self.tz_to_loc[timezone]
KeyError: 'America/Montreal'
2018-09-05 13:08:37 [DEBUG] connectionpool.py(393) _make_request(): https://notify.bugsnag.com:443 "POST / HTTP/1.1" 200 2
```

**Comment by willsir14** [comment]
Select your location; unable to find my location
and 
Select your timezone; blank page
