### ISSUE TITLE
SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!

### ISSUE THREAD

**Issue by ntfs1984** [Antergos/Cnchi#1108]
```

2018-10-28 16:54:22 [DEBUG  ] https://mirror.nl.leaseweb.net:443 "GET /antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-28 16:54:22 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-28 16:54:22 [DEBUG  ] Can't download https://mirror.nl.leaseweb.net/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-28 16:54:22 [INFO   ] Fetching antergos-desktop-settings 1.14-1 (39/826)...  (slides.py:240)
2018-10-28 16:54:42 [DEBUG  ] Starting new HTTPS connection (1): ftp.acc.umu.se:443  (connectionpool.py:823)
2018-10-28 16:54:42 [DEBUG  ] https://ftp.acc.umu.se:443 "GET /mirror/antergos.com/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-28 16:54:43 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-28 16:54:43 [DEBUG  ] Can't download https://ftp.acc.umu.se/mirror/antergos.com/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-28 16:55:03 [DEBUG  ] Starting new HTTPS connection (1): mirror.alpix.eu:443  (connectionpool.py:823)
2018-10-28 16:55:03 [DEBUG  ] https://mirror.alpix.eu:443 "GET /antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-28 16:55:04 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-28 16:55:04 [DEBUG  ] Can't download https://mirror.alpix.eu/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-28 16:55:24 [DEBUG  ] Starting new HTTPS connection (1): glua.ua.pt:443  (connectionpool.py:823)
2018-10-28 16:55:25 [DEBUG  ] https://glua.ua.pt:443 "GET /pub/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-28 16:55:28 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-28 16:55:28 [DEBUG  ] Can't download https://glua.ua.pt/pub/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-28 16:55:48 [DEBUG  ] Starting new HTTPS connection (1): antergos.mirror.constant.com:443  (connectionpool.py:823)
2018-10-28 16:55:49 [DEBUG  ] https://antergos.mirror.constant.com:443 "GET /antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-28 16:55:50 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-28 16:55:50 [DEBUG  ] Can't download https://antergos.mirror.constant.com/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-28 16:56:10 [DEBUG  ] Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443  (connectionpool.py:823)
2018-10-28 16:56:12 [DEBUG  ] https://mirrors.tuna.tsinghua.edu.cn:443 "GET /antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-28 16:56:15 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-28 16:56:15 [DEBUG  ] Can't download https://mirrors.tuna.tsinghua.edu.cn/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-28 16:56:35 [ERROR  ] Can't download antergos-desktop-settings-1.14-1-any.pkg.tar.xz, even after trying all available mirrors  (download_requests.py:185)
2018-10-28 16:56:35 [ERROR  ] "Can't download needed packages. Cnchi can't continue."  (process.py:185)
2018-10-28 16:56:35 [ERROR  ] Traceback (most recent call last):  (process.py:190)
2018-10-28 16:56:35 [ERROR  ]   File "/usr/share/cnchi/src/installation/process.py", line 167, in run
    self.pkg.packages, self.down.metalinks)  (process.py:190)
2018-10-28 16:56:35 [ERROR  ]   File "/usr/share/cnchi/src/pages/advanced.py", line 1792, in run_install
    self.installation.run()  (process.py:190)
2018-10-28 16:56:35 [ERROR  ]   File "/usr/share/cnchi/src/misc/extra.py", line 194, in helper
    return func(*args, **kwargs)  (process.py:190)
2018-10-28 16:56:35 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 296, in run
    self.download_packages()  (process.py:190)
2018-10-28 16:56:35 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 356, in download_packages
    download_packages.start_download(self.metalinks)  (process.py:190)
2018-10-28 16:56:35 [ERROR  ]   File "/usr/share/cnchi/src/download/download.py", line 114, in start_download
    raise misc.InstallError(txt)  (process.py:190)
2018-10-28 16:56:35 [ERROR  ] misc.extra.InstallError: "Can't download needed packages. Cnchi can't continue."  (process.py:190)
2018-10-28 16:56:35 [DEBUG  ] Starting new HTTP connection (1): build.antergos.com:80  (connectionpool.py:205)
2018-10-28 16:56:36 [DEBUG  ] http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 301 None  (connectionpool.py:393)
2018-10-28 16:56:36 [DEBUG  ] http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 200 None  (connectionpool.py:393)
```

**Comment by karasu** [comment]
Something must be wrong with the `antergos-desktop-settings` package. I will rebuild it. Thanks for the warning.

**Comment by karasu** [comment]
Thanks @lots0logs for fixing this :grinning:

**Comment by karasu** [comment]
@etaggus are you still experiencing this? Take into account that some mirrors can take 24 hours to update.

**Comment by ntfs1984** [comment]
Guys, I'm active user of Antergos, additionally have free time and few devices, so I can do a tests if necessary.
