### ISSUE TITLE
Antergos Installer - Error

### ISSUE THREAD

**Issue by drujd** [Antergos/Cnchi#1110]
18.10 minimal iso:

```
2018-10-30 10:25:10 [DEBUG  ] Looking for antergos-desktop-settings-1.14-1 in 2 mirrors...  (download_requests.py:212)
2018-10-30 10:25:10 [DEBUG  ] Starting new HTTP connection (1): repo.antergos.info:80  (connectionpool.py:205)
2018-10-30 10:25:11 [DEBUG  ] http://repo.antergos.info:80 "GET /antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-30 10:25:11 [INFO   ] Fetching antergos-desktop-settings 1.14-1 (158/1067)...  (slides.py:240)
2018-10-30 10:25:11 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-30 10:25:11 [DEBUG  ] Can't download http://repo.antergos.info/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-30 10:25:31 [DEBUG  ] Starting new HTTP connection (1): repo.antergos.info:80  (connectionpool.py:205)
2018-10-30 10:25:32 [DEBUG  ] http://repo.antergos.info:80 "GET /antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-30 10:25:33 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-30 10:25:33 [DEBUG  ] Can't download http://repo.antergos.info/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-30 10:25:53 [ERROR  ] Can't download antergos-desktop-settings-1.14-1-any.pkg.tar.xz, even after trying all available mirrors  (download_requests.py:185)
2018-10-30 10:25:53 [ERROR  ] "Can't download needed packages. Cnchi can't continue."  (process.py:185)
2018-10-30 10:25:53 [ERROR  ] Traceback (most recent call last):  (process.py:190)
2018-10-30 10:25:53 [ERROR  ]   File "/usr/share/cnchi/src/installation/process.py", line 167, in run
    self.pkg.packages, self.down.metalinks)  (process.py:190)
2018-10-30 10:25:53 [ERROR  ]   File "/usr/share/cnchi/src/pages/automatic.py", line 281, in run_install
    self.installation.run()  (process.py:190)
2018-10-30 10:25:53 [ERROR  ]   File "/usr/share/cnchi/src/misc/extra.py", line 194, in helper
    return func(*args, **kwargs)  (process.py:190)
2018-10-30 10:25:53 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 296, in run
    self.download_packages()  (process.py:190)
2018-10-30 10:25:53 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 356, in download_packages
    download_packages.start_download(self.metalinks)  (process.py:190)
2018-10-30 10:25:53 [ERROR  ]   File "/usr/share/cnchi/src/download/download.py", line 114, in start_download
    raise misc.InstallError(txt)  (process.py:190)
2018-10-30 10:25:53 [ERROR  ] misc.extra.InstallError: "Can't download needed packages. Cnchi can't continue."  (process.py:190)
2018-10-30 10:25:53 [DEBUG  ] Starting new HTTP connection (1): build.antergos.com:80  (connectionpool.py:205)
2018-10-30 10:25:53 [DEBUG  ] http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 301 None  (connectionpool.py:393)
2018-10-30 10:25:54 [DEBUG  ] http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 200 None  (connectionpool.py:393)
```

**Comment by karasu** [comment]
@lots0logs 

antergos-desktop-settings package is faulty. I think it's my fault, bug I do not know what I did wrong.

**Comment by xenithorb** [comment]
Something must be seriously messed up with packages/repositories right now because I can't get through an install of even GNOME or DDE without it complaining about "Error creating metalink for package" 

I've run into `antergos-midnight-timers`, `ttf-bitstream-vera`, and now `ffmpegthumbnailer` thus far as I try different DEs and install paths to try and get this working.

What is the root of the issue here and why are so many of us having this problem? Days ago I did a test in a few VMs and loved the experience, but now that this underbelly bug of antergos has reared its ugly head I'm really questioning whether or not I want to continue here

**Comment by xenithorb** [comment]
```
Air Naval Gunfire Liaison Companies (ANGLICO) are airborne fire support and liaison units of the United States Marine Corps. The mission of ANGLICO is "To provide Marine Air-Ground Task Force (MAGTF) Commanders a liaison capability to plan, coordinate, and conduct terminal control of fires in support of joint, allied, and coalition forces."[1] Per this mission statement, ANGLICOs are not designed to support U.S. Marine Corps maneuver elements. Instead, the doctrinal purpose of ANGLICO is to provide fire support and coordination in support of units adjacent to the MAGTF. 
```

**Comment by xenithorb** [comment]
```
018-11-15 10:03:22 [WARNING] /dev/vda: unrecognised disk label  (populate_devices.py:95)
2018-11-15 10:03:24 [DEBUG  ] Cnchi is ranking your mirrors lists...  (mirrors.py:404)
2018-11-15 10:03:24 [DEBUG  ] Updating both mirrorlists (Arch and Antergos)...  (rank_mirrors.py:369)
2018-11-15 10:03:25 [DEBUG  ] Filtering and sorting mirrors...  (rank_mirrors.py:374)
2018-11-15 10:03:25 [DEBUG  ] Starting new HTTP connection (1): www.archlinux.org:80  (connectionpool.py:205)
2018-11-15 10:03:26 [DEBUG  ] http://www.archlinux.org:80 "GET /mirrors/status/json/ HTTP/1.1" 301 185  (connectionpool.py:393)
2018-11-15 10:03:26 [DEBUG  ] Starting new HTTPS connection (1): www.archlinux.org:443  (connectionpool.py:813)
2018-11-15 10:03:26 [DEBUG  ] https://www.archlinux.org:443 "GET /mirrors/status/json/ HTTP/1.1" 200 None  (connectionpool.py:393)
2018-11-15 10:03:27 [DEBUG  ] cryptsetup version is: 2.0.5-1 (used to test mirror speed)  (rank_mirrors.py:166)
2018-11-15 10:03:28 [DEBUG  ] ttf-myanmar3 version is: 20110120-1 (used to test mirror speed)  (rank_mirrors.py:166)
2018-11-15 10:03:28 [DEBUG  ] Server            Rate       Time  (rank_mirrors.py:276)
2018-11-15 10:03:28 [WARNING] https://mirror.host.ag not found in /etc/pacman.d/antergos-mirrorlist  (rank_mirrors.py:155)
2018-11-15 10:03:28 [WARNING] Couldn't download https://repo.antergos.info/antergos/x86_64/ttf-myanmar3-20110120-1-any.pkg.tar.xz  (rank_mirrors.py:221)
2018-11-15 10:03:28 [WARNING] HTTP Error 403: Forbidden  (rank_mirrors.py:222)

```

**Comment by WetGeek** [comment]
On 11/15/2018 1:10 AM, Mike Goodwin wrote:
> Something must be seriously messed up with packages/repositories right 
> now because I can't get through an install of even GNOME or DDE 
> without it complaining about "Error creating metalink for package"

I was able to install it into a VirtualBox VM, but not onto a 
development workstation.  Without a compelling reason to use Antergos, I 
found that Linux Mint v19 + XFCE makes an excellent - and very stable - 
distro that's easy to install.  Might work for you?
