### ISSUE TITLE
Cnchi can't install necessary package

### ISSUE THREAD

**Issue by Fr4nci** [Antergos/Cnchi#1151]
**Describe the bug**
Can't install the necessary packages

**To Reproduce**
1. Complete the installation
2. Wait a while when cnchi installs the many packages for the DE, ecc.
3. After a while you can see the error "Can't install necessary packages"

**Expected behavior**
Cnchi stops working and I need to reboot the live usb to try again the installation.

**Log Files**
/var/log/cnchi/cnchi.log https://paste2.org/dCDhNd6m
The other file was too big (the quantitative of word that there aren't no service that accept the file)

**Comment by Fr4nci** [comment]
PS I was trying to get Deepin as DE.

**Comment by LinuxUserGD** [comment]
I get the same error.

**Comment by LinuxUserGD** [comment]
```
2019-04-15 17:58:08 [INFO   ] Fetching brltty-minimal 6.0-1 (221/1135)...  (slides.py:240)
2019-04-15 17:58:08 [WARNING] SHA256 hash of file brltty-minimal-6.0-1-x86_64.pkg.tar.xz does not match!  (download_hash.py:49)
2019-04-15 17:58:08 [DEBUG  ] Can't download https://mirrors.nic.cz/antergos/antergos/x86_64/brltty-minimal-6.0-1-x86_64.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2019-04-15 17:58:28 [DEBUG  ] Starting new HTTPS connection (1): glua.ua.pt:443  (connectionpool.py:813)
2019-04-15 17:58:29 [DEBUG  ] https://glua.ua.pt:443 "GET /pub/antergos/antergos/x86_64/brltty-minimal-6.0-1-x86_64.pkg.tar.xz HTTP/1.1" 200 1152888  (connectionpool.py:393)
2019-04-15 17:58:29 [WARNING] SHA256 hash of file brltty-minimal-6.0-1-x86_64.pkg.tar.xz does not match!  (download_hash.py:49)
2019-04-15 17:58:29 [DEBUG  ] Can't download https://glua.ua.pt/pub/antergos/antergos/x86_64/brltty-minimal-6.0-1-x86_64.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2019-04-15 17:58:49 [ERROR  ] Can't download brltty-minimal-6.0-1-x86_64.pkg.tar.xz, even after trying all available mirrors  (download_requests.py:185)
2019-04-15 17:58:49 [ERROR  ] "Can't download needed packages. Cnchi can't continue."  (process.py:185)
2019-04-15 17:58:49 [ERROR  ] Traceback (most recent call last):  (process.py:190)
2019-04-15 17:58:49 [ERROR  ]   File "/usr/share/cnchi/src/installation/process.py", line 167, in run
    self.pkg.packages, self.down.metalinks)  (process.py:190)
2019-04-15 17:58:49 [ERROR  ]   File "/usr/share/cnchi/src/pages/advanced.py", line 1792, in run_install
    self.installation.run()  (process.py:190)
2019-04-15 17:58:49 [ERROR  ]   File "/usr/share/cnchi/src/misc/extra.py", line 194, in helper
    return func(*args, **kwargs)  (process.py:190)
2019-04-15 17:58:49 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 296, in run
    self.download_packages()  (process.py:190)
2019-04-15 17:58:49 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 356, in download_packages
    download_packages.start_download(self.metalinks)  (process.py:190)
2019-04-15 17:58:49 [ERROR  ]   File "/usr/share/cnchi/src/download/download.py", line 114, in start_download
    raise misc.InstallError(txt)  (process.py:190)
2019-04-15 17:58:49 [ERROR  ] misc.extra.InstallError: "Can't download needed packages. Cnchi can't continue."  (process.py:190)
2019-04-15 17:58:49 [DEBUG  ] Starting new HTTP connection (1): build.antergos.com:80  (connectionpool.py:205)
2019-04-15 17:58:50 [DEBUG  ] http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 301 None  (connectionpool.py:393)
2019-04-15 17:58:50 [DEBUG  ] http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 200 None  (connectionpool.py:393)
```

**Comment by LinuxUserGD** [comment]
From the official website: "BRLTTY is a background process (daemon) which provides access to the Linux/Unix console (when in text mode) for a blind person using a refreshable braille display." So it should work by deselecting it.
