### ISSUE TITLE
Cnchi is forgetting to install the Pacman GPG keys, and overlooks the error message for the issue!

### ISSUE THREAD

**Issue by WokSearedBacon** [Antergos/Cnchi#237]
When using the latest 11.28 iso with the default Cnchi version, when run with 'su cnchi -d' Cnchi seems to move along well without any apparent errors, but when I look at the log, it appears to have a few.

One of these is that Cnchi fails to find the file containing the GPG keys for Pacman, and if you let Cnchi install a system, it renders the system absolutely unable to install packages via pacman, whether its GIMP, Firefox, or Hexchat.

Here is the particular log message:
```
2014-11-28 09:51:03] [process.py] ERROR: [Errno 6] No such device or address: '/etc/pacman.d/gnupg/S.gpg-agent'
Traceback (most recent call last):
  File "/usr/share/cnchi/src/installation/process.py", line 449, in prepare_pacman_keychain
    misc.copytree('/etc/pacman.d/gnupg', dest_path)
  File "/usr/share/cnchi/src/canonical/misc.py", line 41, in copytree
    shutil.copy2(s, d)
  File "/usr/lib/python3.4/shutil.py", line 244, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.4/shutil.py", line 107, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 6] No such device or address: '/etc/pacman.d/gnupg/S.gpg-agent'
```

**Comment by WokSearedBacon** [comment]
From what I've seen, the keys have been copied in without a hitch.
