### ISSUE TITLE
Cnchi 0.6.44 hangs on formatting

### ISSUE THREAD

**Issue by Xarin** [Antergos/Cnchi#266]
It happens after I set up all my partitions, and hit next.
Traceback (most recent call last):
  File "/usr/share/cnchi/src/mainwindow.py", line 308, in on_forward_button_clicked
    stored = self.current_page.store_values()
  File "/usr/share/cnchi/src/installation/advanced.py", line 1661, in store_values
    self.create_staged_partitions()
  File "/usr/share/cnchi/src/installation/advanced.py", line 1753, in create_staged_partitions
    fs.label_fs(fisy, partition_path, lbl)
  File "/usr/share/cnchi/src/canonical/misc.py", line 163, in helper
    return func(*args, **kwargs)
  File "/usr/share/cnchi/src/parted3/fs_module.py", line 80, in label_fs
    result = subprocess.check_output(shlex.split(ladic[fstype] % vars())).decode()
KeyError: 'swap'

(cnchi.log)
[2015-02-24 21:26:54] [mainwindow.py] INFO: Cnchi installer version 0.6.44
[2015-02-24 21:27:09] [timezone.py] INFO: We have connection. Let's get our timezone
[2015-02-24 21:27:10] [timezone.py] INFO: Timezone detected.
[2015-02-24 21:27:11] [check.py] INFO: We have Internet connection.
[2015-02-24 21:27:11] [check.py] INFO: We're connected to a power source.
[2015-02-24 21:27:11] [check.py] INFO: We have enough disk space.
[2015-02-24 21:27:11] [connectionpool.py] INFO: Starting new HTTP connection (1): www.archlinux.org
[2015-02-24 21:27:11] [connectionpool.py] INFO: Starting new HTTPS connection (1): www.archlinux.org
[2015-02-24 21:27:18] [location.py] INFO: locale changed to : en_US.UTF-8
[2015-02-24 21:27:18] [timezone.py] INFO: location changed to : America/New_York
[2015-02-24 21:27:18] [timezone.py] INFO: location changed to : America/New_York
[2015-02-24 21:27:23] [keymap.py] INFO: keyboard_layout is USA
[2015-02-24 21:27:29] [desktop.py] INFO: Cnchi will install Antergos with the 'cinnamon' desktop
[2015-02-24 21:35:35] [advanced.py] INFO: Creating new ext4 filesystem in /dev/sda6 labeled Boot
[2015-02-24 21:35:39] [advanced.py] INFO: 
[2015-02-24 21:35:39] [advanced.py] INFO: Creating new swap filesystem in /dev/sda5 labeled Swap

**Comment by Xarin** [comment]
Seems it does not like you labeling the swap partition.

**Comment by karasu** [comment]
Thanks for your detailed report. I'll try to fix it asap and get back to you.

**Comment by karasu** [comment]
You were right. Labeling a swap partition was unsupported.

I've fixed it but I haven't the time to test it, I have to rush to work. If you want to be safe just refrain yourself from labeling a swap partition :grin:

Thanks!

**Comment by Xarin** [comment]
Haha, thanks for the quick turnaround!
