### ISSUE TITLE
Antergos Installer - Libreoffice feature is not working

### ISSUE THREAD

**Issue by Deevad** [Antergos/Cnchi#283]
Cnchi version: 0.8.7
Iso: antergos-minimal-2015.04.12-x86_64
Region/locale: en-US
Keyboard/location : Paris / French alternative
Options : AUR / Printing services
D.E. : tested with KDE and OpenBox

Error message ( weird , because appear in french ):
[Erno 2] Aucun fichier ou dossier de ce type :'/install/etc/X11/xorg.conf.d/10-keyboard.conf'
( mean 'no file or folder found :'/install/etc/X11/xorg.conf.d/10-keyboard.conf' )

it happens during the slideshow installer at 'Adjusting hardware clock'. The modal dialog only propose close ( in french also ; 'Fermer' ). Also the minimal ISO don't have terminal or launcher or any button to close the system when Cnchi fail and close. I need to press 6 second the hardware reset button to close.

**Comment by karasu** [comment]
Thanks for reporting it.
It seems there are two issues here. We'll leave the language one for later.
We'll get back to you when we have more information.
By the way, did you grab the log from the tmp directory? That would be useful, if not do not worry, we'll try to reproduce the error here.

**Comment by Deevad** [comment]
Ok, thank you for the fast reply.

Here is the full /tmp/cnchi.log : 
http://www.pasteall.org/57815/text

Here is probably the revelant part (missing sed ? ) :
```
[2015-04-13 07:11:28] [chroot] DEBUG: Generating locales...
/usr/bin/locale-gen: line 33: sed: command not found
  .UTF-8/usr/bin/locale-gen: line 35: sed: command not found
.../usr/bin/locale-gen: line 38: sed: command not found
[2015-04-13 07:11:28] [slides] INFO: Installing lib32-mesa-libgl (127/128)
[2015-04-13 07:11:28] [slides] INFO: Installing xf86-video-nouveau (128/128)
[2015-04-13 07:11:28] [slides] INFO: Configuring your new system
[2015-04-13 07:11:28] [slides] INFO: Generating locales...
[2015-04-13 07:11:28] [slides] INFO: Adjusting hardware clock...
[2015-04-13 07:11:29] [process] DEBUG: Set /etc/X11/xorg.conf.d/10-keyboard.conf for the xkblayout
[2015-04-13 07:11:29] [process] ERROR: [Errno 2] Aucun fichier ou dossier de ce type: '/install/etc/X11/xorg.conf.d/10-keyboard.conf'
[2015-04-13 07:11:29] [process] ERROR: ['Traceback (most recent call last):\n', '  File "/usr/share/cnchi/cnchi/installation/process.py", line 166, in run\n    self.run_installation()\n', '  File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper\n    return func(*args, **kwargs)\n', '  File "/usr/share/cnchi/cnchi/installation/process.py", line 355, in run_installation\n    self.configure_system()\n', '  File "/usr/share/cnchi/cnchi/installation/process.py", line 1333, in configure_system\n    with open(xorg_conf_xkb_path, "w") as xorg_conf_xkb:\n', "FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/install/etc/X11/xorg.conf.d/10-keyboard.conf'\n"]
[2015-04-13 07:11:29] [show_message] ERROR: [Errno 2] Aucun fichier ou dossier de ce type: '/install/etc/X11/xorg.conf.d/10-keyboard.conf'
```

**Comment by karasu** [comment]
I've seen there are a LOT of dependency problems in your log. Let me check it.

**Comment by Deevad** [comment]
Also, it's weird ; I read a lot of ```lib32*``` things in my log ; but I use the ```x86_64``` ISO.

**Comment by karasu** [comment]
I was wrong, as pacman solves those dependencies. The lib32 is because Cnchi installs some multilib libraries (like lib32-mesa) needed if you run some 32bit apps (mostly games).

**Comment by karasu** [comment]
Some things from the log (I'll post them here for future reference, but maybe they're not related to the issue).

`[2015-04-13 10:57:59] [process] WARNING: Couldn't find grub2 bootloader packages!`

```
[2015-04-13 07:11:28] [process] WARNING: Can't find pacman configuration file
[2015-04-13 07:11:28] [process] DEBUG: Generated /etc/pacman.conf
[2015-04-13 07:11:28] [process] WARNING: Can't find service lightdm
[2015-04-13 07:11:28] [process] WARNING: Can't find service ModemManager
[2015-04-13 07:11:28] [process] WARNING: Can't find service NetworkManager
[2015-04-13 07:11:28] [process] WARNING: Can't find service remote-fs.target
[2015-04-13 07:11:28] [process] WARNING: Can't find service haveged
```

```
[2015-04-13 07:11:28] [chroot] DEBUG: Generating locales.../usr/bin/locale-gen: line 33: sed: command not found  .UTF-8/usr/bin/locale-gen: line 35: sed: command not found.../usr/bin/locale-gen: line 38: sed: command not found
```

```
[2015-04-13 07:11:29] [process] DEBUG: Set /etc/X11/xorg.conf.d/10-keyboard.conf for the xkblayout
[2015-04-13 07:11:29] [process] ERROR: [Errno 2] Aucun fichier ou dossier de ce type: '/install/etc/X11/xorg.conf.d/10-keyboard.conf'
[2015-04-13 07:11:29] [process] ERROR: ['Traceback (most recent call last):\n', '  File "/usr/share/cnchi/cnchi/installation/process.py", line 166, in run\n    self.run_installation()\n', '  File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper\n    return func(*args, **kwargs)\n', '  File "/usr/share/cnchi/cnchi/installation/process.py", line 355, in run_installation\n    self.configure_system()\n', '  File "/usr/share/cnchi/cnchi/installation/process.py", line 1333, in configure_system\n    with open(xorg_conf_xkb_path, "w") as xorg_conf_xkb:\n', "FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/install/etc/X11/xorg.conf.d/10-keyboard.conf'\n"]
[2015-04-13 07:11:29] [show_message] ERROR: [Errno 2] Aucun fichier ou dossier de ce type: '/install/etc/X11/xorg.conf.d/10-keyboard.conf'
```

**Comment by robertda** [comment]
Is not possible to downgrade cnchi to 0.6.3?
I have also march minimal iso, but cnchi update to 0.8.0 / 0.8.3 / 0.8.5 / 0.8.7 and all install is affected.
Try to cheat by disable network during setup first steps and re-plugged on package download, by cnchi caught me and download a new faulty version and reload setup.

All package list, sudoers and keyboard errors encountered.

Due to Distrowatch announce, lot of users will try to install and none of it will succeed. Please, revert to 0.6.3 somehow.

**Comment by Deevad** [comment]
I confirm what @robertda said. I installed Antergos last week on laptop with previous ISO and installer without any issue, and tested many flavors of D.E ; and learnt how to migrate all my 'buntu previous workflow to Arch how-to and wiki method ( lamp server, color calibration, wacom tablet setup, dual screen with nvidia, building high perf vectorisation lib for graphical apps like Krita ).

This sunday I wanted to reinstall my main workstation to something similar I made on laptop last week. But so far, the experience is a bit bitter : New Cnchi, Gnome 3.16 (ruining my laptop with Cinnamon, but fixed now ) and I'm trying to flee to KDE ecosystem when I see it's a big mixed situation of qt5/Plasma 5 and old kde4 apps...

I'm on monday and workstation is still a prompt with a grub error, I also experienced yesterday all cnchi 0.8.0 to 0.8.6 updates bugs...

I know you are doing your best , and all my encouragements. But for the side of user ; it's a very frustrating situation.

**Comment by Deevad** [comment]
Ok, I think this problem is solved with 0.8.11 : I just tested. 
Thanks for the hard work. 

Now, I only get the missing GRUB at restart ; the minimal ISO propose a dialog to open the Arch GRUB page on wiki at the end ; but with minimal ISO it's hard to work.

**Comment by karasu** [comment]
The missing Grub is solved in 0.8.12, I think @lots0logs is updating it at this very moment.

**Comment by Jbonnett** [comment]
I am having this issue as well. How could i pull in your latest patch? I have both desktop and minimal usb disks.

**Comment by pilppe** [comment]
Same issue, resorted to Ubuntu GNOME since i didnt have any OS

**Comment by karasu** [comment]
@Jbonnett @pilppe : Did you wait for Cnchi to update itself? It has to be, at least, version 0.8.11 (for the grub solution it's, at least, 0.8.15)

We've tested in different computers and is working. Please try it again when you have the time.

**Comment by Jbonnett** [comment]
Just tried again, same problem. Waited for the update notification and then restarted cnchi, but got the exact same error.

**Comment by pilppe** [comment]
@karasu i will never leave Glorious Antergos, in the meantime ill wait for the Cnchi to get fixed and ill continue translating Cnchi to Finnish :)

**Comment by Jbonnett** [comment]
looks like I am running cnchi 0.8.16, from the log

**Comment by karasu** [comment]
@Jbonnett and @pilppe :That's odd... did you grab the log by any chance? I'll have a look at it. Also, which DE and options did you choose? I do not get it as it's working here... maybe  you're getting an old mirror all the time, dunno.

@pilppe : Thanks for the translations, I know can be tedious sometimes, but I guarantee you that it's greatly appreciated!

**Comment by pilppe** [comment]
If you want this info, This is how i install:
DE:Cinnamon
BOOTLOADER:Grub2
Options: All of them checked

Also, @karasu sometimes the installer cannot format to EXT4, and some other issues which i will see when i try again tomorrow, the only fix is to manually partition but that usually ends with the same error as this issue

**Comment by karasu** [comment]
OK, I'll try to check Cinnamon here, maybe that's the problem (I just tested Gnome and Mate, today).

**Comment by Jbonnett** [comment]
http://slexy.org/view/s2CFDNtzE6
DE: gnome, 
features: everything except ufw and firefox
custom partitions, grub on a particular disk

**Comment by karasu** [comment]
mmmm... it's like is trying to install a package that does not exist. Let me do some tests...

**Comment by karasu** [comment]
Yep, in Cinnamon, using no extras, works for me. If you want to try again, please unselect all "extras" in the features screen. That should do the trick.

**Comment by pilppe** [comment]
@karasu I want to use AUR and have printer support

**Comment by Jbonnett** [comment]
Aur and printer + gnome seems to be installing now?

**Comment by karasu** [comment]
After doing some tests, it's the libreoffice option that does not work here in Cinnamon. I'll now check all the Gnome options.

**Comment by karasu** [comment]
OK, Gnome + all options EXCEPT printing support works. Please confirm when you have the time.

**Comment by karasu** [comment]
Sorry, I meant that Gnome + all options EXCEPT libreoffice works. Please try it again WITHOUT selecting libreoffice when you have the time and report it here.
Thanks for your help!

**Comment by Jbonnett** [comment]
Finished, worked except bootloader (probably related to my setup, will check and report a ticket if need be)  

unrelated but needs fixing: The wiki linkto the bootloader docs ( shown when grub install fails )  redirects to the antergos front page now.

**Comment by karasu** [comment]
@Jbonnett : Glad it worked! If you have any problems fixing the bootloader please ask in our forum, too. Oh, we'll fix that link asap. Thanks for your patience.
