### ISSUE TITLE
User Info Screen UI Bugs

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#318]
- [ ] Button should be the regular forward icon.

![screenshot from 2015-04-29 01-22-47](https://cloud.githubusercontent.com/assets/4675662/7383411/6f1f2f0a-ee0e-11e4-82ba-941e62a8050a.png)

**Comment by cesarcifmetal** [comment]
It still with no forward icon.
![screenshot from 2015-05-01 06-45-19](https://cloud.githubusercontent.com/assets/6477454/7428833/b40b2130-efcd-11e4-8613-f3b181a4453a.png)

**Comment by lots0logs** [comment]
@cesarcifmetal Thanks for testing it. I'll take another look today.

**Comment by cesarcifmetal** [comment]
Now, can't format a labeled partition, and there is the install now buttom, but it has lost all the fields to create the user and pass.
![screenshot from 2015-05-01 16-44-58](https://cloud.githubusercontent.com/assets/6477454/7433527/b3795706-f021-11e4-8400-7bd025a921ad.png)
![screenshot from 2015-05-01 16-46-35](https://cloud.githubusercontent.com/assets/6477454/7433528/b3a1faf8-f021-11e4-82f6-700fb5ca6c2b.png)

**Comment by lots0logs** [comment]
Could you post the log when the blank user info screen appears? Thanks.

**Comment by karasu** [comment]
@lots0logs : There's a bug in fs_module.py, in create_fs function. It fails when no label is given. I'll fix it asap.

**Comment by cesarcifmetal** [comment]
@lots0logs : Sorry im too noob to do that on my own, could you tell me how? thanks.

**Comment by cesarcifmetal** [comment]
@lots0logs : could be this?  
 File "/home/antergos/cnchi/cnchi/user_info.py", line 211, in prepare
    self.forward_button.set_label(None)
TypeError: Argument 1 does not allow None as a value

**Comment by karasu** [comment]
@cesarcifmetal : Yep, I think that's it

**Comment by cesarcifmetal** [comment]
@karasu Thanks.

**Comment by cesarcifmetal** [comment]
At the 0.8.88 version, the forward buttom at the user info page is not there again.

**Comment by cesarcifmetal** [comment]
@lots0logs take a look on this

[antergos@Antergos-ISO ~]$ sudo pacman -S git
resolving dependencies...
looking for conflicting packages...

Packages (1) git-2.3.7-1

Total Download Size:    4.04 MiB
Total Installed Size:  24.00 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages ...
 git-2.3.7-1-x86_64         4.0 MiB   125K/s 00:33 [######################] 100%
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
(1/1) upgrading git                                [######################] 100%
[antergos@Antergos-ISO ~]$ sudo rm -rf /usr/share/cnchi
[antergos@Antergos-ISO ~]$ git clone https://github.com/Antergos/cnchi --depth=1
Cloning into 'cnchi'...
remote: Counting objects: 539, done.
remote: Compressing objects: 100% (442/442), done.
remote: Total 539 (delta 118), reused 435 (delta 90), pack-reused 0
Receiving objects: 100% (539/539), 6.19 MiB | 128.00 KiB/s, done.
Resolving deltas: 100% (118/118), done.
Checking connectivity... done.
[antergos@Antergos-ISO ~]$ cd cnchi
[antergos@Antergos-ISO cnchi]$ ./run
rm: cannot remove ‘/usr/share/cnchi’: No such file or directory
[2015-05-02 12:18:25] [cnchi] INFO: Using GTK v3.16.1
[2015-05-02 12:18:25] [cnchi] INFO: Using pyalpm v0.7 as interface to libalpm v9.0.1
[2015-05-02 12:18:29] [updater] INFO: Cnchi Internet version: 0.8.87
[2015-05-02 12:18:30] [main_window] INFO: Cnchi installer version 0.8.99
[2015-05-02 12:18:30] [main_window] DEBUG: Cnchi will use '/var/cache/pacman/pkg' as a source directory for cached xz packages
[2015-05-02 12:18:30] [main_window] INFO: Using '/usr/share/cnchi/data/packages.xml' file as package list
[2015-05-02 12:18:30] [gtkbasebox] DEBUG: Loading 'welcome' screen
Traceback (most recent call last):
  File "cnchi/cnchi.py", line 70, in do_activate
    window = main_window.MainWindow(self, cmd_line)
  File "/home/antergos/cnchi/cnchi/main_window.py", line 245, in __init__
    style_provider.load_from_data(css_data)
GLib.Error: gtk-css-provider-error-quark: <data>:93:22Expected a valid selector (1)

**Comment by karasu** [comment]
@cesarcifmetal : thanks. Version 0.8.100 should start fine. I haven't tested @lots0logs changes, though.

**Comment by cesarcifmetal** [comment]
@karasu i will test it now. thanks.

**Comment by cesarcifmetal** [comment]
@karasu please take a look on this.

[2015-05-02 15:10:52] [cnchi] INFO: Using GTK v3.16.1
[2015-05-02 15:10:52] [cnchi] INFO: Using pyalpm v0.7 as interface to libalpm v9.0.1
[2015-05-02 15:11:35] [updater] INFO: Cnchi Internet version: 0.8.87
[2015-05-02 15:11:35] [main_window] INFO: Cnchi installer version 0.8.100
[2015-05-02 15:11:35] [main_window] DEBUG: Cnchi will use '/var/cache/pacman/pkg' as a source directory for cached xz packages
[2015-05-02 15:11:35] [main_window] INFO: Using '/usr/share/cnchi/data/packages.xml' file as package list
[2015-05-02 15:11:35] [gtkbasebox] DEBUG: Loading 'welcome' screen
[2015-05-02 15:11:38] [gtkbasebox] DEBUG: Loading 'language' screen
Traceback (most recent call last):
  File "/home/antergos/cnchi/cnchi/main_window.py", line 391, in on_forward_button_clicked
  File "/home/antergos/cnchi/cnchi/main_window.py", line 275, in load_pages
  File "/home/antergos/cnchi/cnchi/language.py", line 43, in __init__
  File "/home/antergos/cnchi/cnchi/gtkbasebox.py", line 57, in __init__
GLib.Error: g-file-error-quark: Failed to open file '/usr/share/cnchi/ui/language.ui': No such file or directory (4)
[2015-05-02 15:11:48] [gtkbasebox] DEBUG: Loading 'language' screen
Traceback (most recent call last):
  File "/home/antergos/cnchi/cnchi/main_window.py", line 391, in on_forward_button_clicked
  File "/home/antergos/cnchi/cnchi/main_window.py", line 275, in load_pages
  File "/home/antergos/cnchi/cnchi/language.py", line 43, in __init__
  File "/home/antergos/cnchi/cnchi/gtkbasebox.py", line 57, in __init__
GLib.Error: g-file-error-quark: Failed to open file '/usr/share/cnchi/ui/language.ui': No such file or directory (4)
[2015-05-02 15:12:00] [gtkbasebox] DEBUG: Loading 'language' screen
Traceback (most recent call last):
  File "/home/antergos/cnchi/cnchi/main_window.py", line 391, in on_forward_button_clicked
  File "/home/antergos/cnchi/cnchi/main_window.py", line 275, in load_pages
  File "/home/antergos/cnchi/cnchi/language.py", line 43, in __init__
  File "/home/antergos/cnchi/cnchi/gtkbasebox.py", line 57, in __init__
GLib.Error: g-file-error-quark: Failed to open file '/usr/share/cnchi/ui/language.ui': No such file or directory (4)
[2015-05-02 15:12:02] [main_window] INFO: Quiting installer...

**Comment by karasu** [comment]
Something is wrong with your installation... check that you have the ui files in /usr/share/cnchi/ui folder.

**Comment by cesarcifmetal** [comment]
I am trying to install Antergos from a live USB, it is like the 20th time that i try it, i am using the issue 303 to get cnchi running, reboot after reboot the installation is not succeded

**Comment by cesarcifmetal** [comment]
@karasu sorry to bother you again, but after cnchi has completed the download of 828 packages, it frozen at loading packages, and just quits.

**Comment by karasu** [comment]
Hi @cesarcifmetal , do not worry, it's not a bother, on the contrary, your comments are very helpful.

Going to bed atm, I will check it tomorrow. Just two things:
- Which DE are you trying to install?
- Are you selecting any features (like firefox, libreoffice, ...)?

If you have the log, post it on pastebin or a similar service and reference it here, please.

**Comment by cesarcifmetal** [comment]
@karasu Thanks, well am trying to install the Gnome version, just with the printer services and AUR.

I think this may be a log

http://pastebin.com/4u3C9UTy

**Comment by karasu** [comment]
@cesarcifmetal
- It's better to reboot after a failed installation, do it before retrying.
- There's a bad download in your package cache. If I understood right and you're running from an USB, Cnchi is trying to use the packages from the previous tries, and there is one package that is not valid (I would guess that is not fully downloaded).

From your log:
```
[2015-05-02 23:13:53] [pac] DEBUG: checking sha256sum for /install/var/cache/pacman/pkg/baobab-3.16.1-1-x86_64.pkg.tar.xz
[2015-05-02 23:13:53] [pac] ERROR: returning error 33 from check_validity : paquete no válido o dañado
```

Please, reboot your computer and try it again, issuing a git clone to get the latest  Cnchi version, and make sure the baobab package is not in your cache (default cache dir: /var/cache/pacman/pkg)

Thanks in advance!

**Comment by cesarcifmetal** [comment]
@karasu ok, will see.
Im using the 0.8.100 version of cnchi, from github.

Thanks to you.
Will got out of internet connection soon, hope to test it and obtain a positive installation.

**Comment by cesarcifmetal** [comment]
@karasu Still unable to install.

**Comment by cesarcifmetal** [comment]
@lots0logs @karasu Hello again, here is another log.
http://pastebin.com/j707C4dz

**Comment by karasu** [comment]
@cesarcifmetal : I'm terribly sorry, you got me in the middle of an update and I had to left it as it was (I was at work). It should be working now... (I have tested it here, and works, but I'm still facing some kind of problem with os-prober when running grub-mkconfig, in the end of the installation). If this happens to you, just wait until Cnchi times out. Everything will be find, but you'll have to run grub-mkconfig yourself.

Oh, I've just installed Gnome3 fine, so I'm afraid that if you can't it must be some mirror problem.

**Comment by cesarcifmetal** [comment]
@lots0logs @karasu Finally, i've got installed correctly. Thanks a lot!!

**Comment by karasu** [comment]
@cesarcifmetal : Wow! I'm sorry about the difficulties... and you're welcome!
