### ISSUE TITLE
Cannot perform Choose exactly where Antergos should be installed

### ISSUE THREAD

**Issue by hypn0s** [Antergos/Cnchi#341]
Hello,

I'm just installing my new machine but I cannot perform and advanced install. When I select "Choose exactly where Antergos should be installed", the following error appears:
```
[2015-05-17 17:30:13] [features] DEBUG: Selected 'firefox' feature to install
[2015-05-17 17:30:13] [features] DEBUG: Selected 'fonts' feature to install
[2015-05-17 17:30:13] [features] DEBUG: Selected 'office' feature to install
Traceback (most recent call last):
  File "/home/antergos/Cnchi/cnchi/main_window.py", line 405, in on_forward_button_clicked
    self.current_page.prepare('forwards')
  File "/home/antergos/Cnchi/cnchi/installation/advanced.py", line 1498, in prepare
    self.update_view()
  File "/home/antergos/Cnchi/cnchi/installation/advanced.py", line 826, in update_view
    self.fill_bootloader_device_entry()
  File "/home/antergos/Cnchi/cnchi/installation/advanced.py", line 309, in fill_bootloader_device_entry
    if not self.select_bootdevice(self.bootloader_device_entry, self.bootloader_device):
  File "/home/antergos/Cnchi/cnchi/installation/advanced.py", line 315, in select_bootdevice
    combo_iter = model.get_iter(0)
  File "/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py", line 826, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '0'
```

I have two disks I want to use for separated partitions so this feature would be really helpful.

EDIT:
Antergos versions:
```
[2015-05-17 17:31:49] [updater] INFO: Cnchi Internet version: 0.8.122
[2015-05-17 17:31:49] [main_window] INFO: Cnchi installer version 0.8.130
```

**Comment by karasu** [comment]
@hypn0s : Not sure what is wrong here. Can you try again with the latest version?  (0.8.132)

**Comment by hypn0s** [comment]
Thank's, that worked :-)
Antergos install in progress ;-)

**Comment by hypn0s** [comment]
Thank's, it worked :-)

**Comment by karasu** [comment]
Thanks for reporting it! (you can close it yourself, no problem.)
