### ISSUE TITLE
It looks like the LVM partition size does not get calculated properly when using LVM, LUKS and a seperate home and root partition on UEFI with a GPT disk.

### ISSUE THREAD

**Issue by Wiebelt** [Antergos/Cnchi#355]
Hi, i am trying to install Antergos with LVM, LUKS and a seperate root and home partition but it seems a calculation is off for the LVM partition size which makes it fail.

It fails on the following command:
```
sgdisk --new=2:0:+3815191M --typecode=2:8E00 --change-name=2:ANTERGOS_LVM /dev/sda
```
When i run the command manually from the terminal and change the :+3815191M to :+3815190M the command does work. Gparted also indicates there is only 3815190M space left. 

It probably has something to do with that the /boot partition starts at sector 2048 (when i look at it in gparted, 2048 sectors of 512 bytes is 1 MB).

Full log (snipped out my location):
```
[2015-05-29 21:16:33] [cnchi] INFO: Using GTK v3.16.1
[2015-05-29 21:16:33] [cnchi] INFO: Using pyalpm v0.7 as interface to libalpm v9.0.1
[2015-05-29 21:16:33] [updater] WARNING: Could not find 'update.info' file. Cnchi will not be able to update itself.
[2015-05-29 21:16:33] [main_window] INFO: Cnchi installer version 0.8.137
[2015-05-29 21:16:34] [main_window] INFO: Using urllib to download packages
[2015-05-29 21:16:34] [gtkbasebox] DEBUG: Loading 'welcome' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'language' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'location' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'check' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'desktop' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'features' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'keymap' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'timezone' screen
[2015-05-29 21:16:35] [timezone] DEBUG: We have connection. Let's get our timezone
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'ask' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'automatic' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'advanced' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'user_info' screen
[2015-05-29 21:16:35] [gtkbasebox] DEBUG: Loading 'slides' screen
[2015-05-29 21:16:35] [timezone] DEBUG: Timezone (latitude ...., longitude ....) detected.
[2015-05-29 21:16:38] [check] INFO: We have Internet connection.
[2015-05-29 21:16:38] [check] INFO: We're connected to a power source.
[2015-05-29 21:16:38] [check] INFO: We have enough disk space.
[2015-05-29 21:16:38] [connectionpool] INFO: Starting new HTTP connection (1): www.archlinux.org
[2015-05-29 21:16:38] [connectionpool] DEBUG: "GET /mirrors/status/json/ HTTP/1.1" 301 366
[2015-05-29 21:16:38] [connectionpool] INFO: Starting new HTTPS connection (1): www.archlinux.org
[2015-05-29 21:16:39] [connectionpool] DEBUG: "GET /mirrors/status/json/ HTTP/1.1" 200 None
[2015-05-29 21:16:40] [rank_mirrors] DEBUG: Auto mirror selection has been run successfully
[2015-05-29 21:16:41] [location] DEBUG: Selected location: English (US), United States
[2015-05-29 21:16:41] [location] INFO: locale changed to : en_US.UTF-8
[2015-05-29 21:16:41] [location] DEBUG: Selected country: United States
[2015-05-29 21:16:41] [timezone] INFO: location changed to : Europe/Amsterdam
[2015-05-29 21:16:42] [timezone] DEBUG: timezone human zone: Amsterdam
[2015-05-29 21:16:42] [timezone] DEBUG: timezone country: NL
[2015-05-29 21:16:42] [timezone] DEBUG: timezone zone: Europe/Amsterdam
[2015-05-29 21:16:42] [timezone] DEBUG: timezone human country: Netherlands
[2015-05-29 21:16:42] [timezone] DEBUG: timezone latitude: ...
[2015-05-29 21:16:42] [timezone] DEBUG: timezone longitude: ...
[2015-05-29 21:16:42] [misc] INFO: locale changed to : en_US.UTF-8
[2015-05-29 21:16:43] [misc] INFO: locale changed to : en_US.UTF-8
[2015-05-29 21:16:43] [keymap] DEBUG: Set keyboard to layout name 'USA' (us)
[2015-05-29 21:16:44] [keymap] DEBUG: Set keyboard to layout name 'USA' (us)
[2015-05-29 21:16:45] [desktop] INFO: Cnchi will install Antergos with the 'gnome' desktop
[2015-05-29 21:16:50] [features] DEBUG: Selected 'aur' feature to install
[2015-05-29 21:16:50] [features] DEBUG: Selected 'bluetooth' feature to install
[2015-05-29 21:16:50] [features] DEBUG: Selected 'cups' feature to install
[2015-05-29 21:16:50] [features] DEBUG: Selected 'firefox' feature to install
[2015-05-29 21:16:50] [features] DEBUG: Selected 'firewall' feature to install
[2015-05-29 21:16:50] [features] DEBUG: Selected 'fonts' feature to install
[2015-05-29 21:16:50] [features] DEBUG: Selected 'office' feature to install
[2015-05-29 21:16:50] [features] DEBUG: Selected 'smb' feature to install
[2015-05-29 21:16:56] [ask] INFO: Antergos installation will be encrypted using LUKS
[2015-05-29 21:16:56] [ask] INFO: Antergos will be installed using LVM volumes
[2015-05-29 21:16:56] [ask] INFO: Antergos will be installed using a separate /home volume.
[2015-05-29 21:16:56] [automatic] DEBUG: ATA WDC WD40EZRX-00S [4000 GB] (/dev/sda)
[2015-05-29 21:16:56] [automatic] DEBUG: ATA WDC WD10EARX-00N [1000 GB] (/dev/sdb)
[2015-05-29 21:16:56] [automatic] DEBUG: SanDisk Cruzer [16 GB] (/dev/sdc)
[2015-05-29 21:17:20] [automatic] DEBUG: A root LUKS password has been set
[2015-05-29 21:17:20] [automatic] INFO: Automatic install on /dev/sda
[2015-05-29 21:17:20] [automatic] INFO: Cnchi will install Antergos on device /dev/sda
[2015-05-29 21:17:20] [automatic] INFO: Antergos will install the bootloader 'gummiboot' in device '/dev/sda'
[2015-05-29 21:17:20] [process] DEBUG: Creating partitions and their filesystems in /dev/sda
[2015-05-29 21:17:20] [auto_partition] DEBUG: Total disk size: 3815447MiB
[2015-05-29 21:17:20] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-29 21:17:20] [auto_partition] DEBUG: LVM physical volume size: 3815191MiB
[2015-05-29 21:17:20] [auto_partition] DEBUG: Swap partition size: 7884MiB
[2015-05-29 21:17:20] [auto_partition] DEBUG: Root partition size: 30000MiB
[2015-05-29 21:17:20] [auto_partition] DEBUG: Home partition size: 3777307MiB
[2015-05-29 21:17:23] [auto_partition] DEBUG: sgdisk --new=1:0:+256M --typecode=1:EF00 --change-name=1:ANTERGOS_BOOT /dev/sda
[2015-05-29 21:17:24] [auto_partition] DEBUG: sgdisk --new=2:0:+3815191M --typecode=2:8E00 --change-name=2:ANTERGOS_LVM /dev/sda
[2015-05-29 21:17:24] [auto_partition] ERROR: Error creating a new partition on device /dev/sda
[2015-05-29 21:17:24] [auto_partition] ERROR: Command ['sgdisk', '--new=2:0:+3815191M', '--typecode=2:8E00', '--change-name=2:ANTERGOS_LVM', '/dev/sda'] failed
[2015-05-29 21:17:24] [auto_partition] ERROR: Output: None
[2015-05-29 21:17:24] [process] ERROR: 'Error creating a new partition on device /dev/sda'
[2015-05-29 21:17:24] [process] ERROR: Traceback (most recent call last):

[2015-05-29 21:17:24] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 269, in sgdisk_new
    subprocess.check_call(cmd)

[2015-05-29 21:17:24] [process] ERROR:   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)

[2015-05-29 21:17:24] [process] ERROR: subprocess.CalledProcessError: Command '['sgdisk', '--new=2:0:+3815191M', '--typecode=2:8E00', '--change-name=2:ANTERGOS_LVM', '/dev/sda']' returned non-zero exit status 4

[2015-05-29 21:17:24] [process] ERROR: 
During handling of the above exception, another exception occurred:


[2015-05-29 21:17:24] [process] ERROR: Traceback (most recent call last):

[2015-05-29 21:17:24] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/process.py", line 166, in run
    self.run_installation()

[2015-05-29 21:17:24] [process] ERROR:   File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)

[2015-05-29 21:17:24] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/process.py", line 230, in run_installation
    auto.run()

[2015-05-29 21:17:24] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 713, in run
    sgdisk_new(device, part_num, "ANTERGOS_LVM", part_sizes['lvm_pv'], "8E00")

[2015-05-29 21:17:24] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 275, in sgdisk_new
    raise InstallError(txt)

[2015-05-29 21:17:24] [process] ERROR: misc.misc.InstallError: 'Error creating a new partition on device /dev/sda'

[2015-05-29 21:17:33] [slides] INFO: Installing using the 'automatic' method
[2015-05-29 21:17:33] [show_message] ERROR: 'Error creating a new partition on device /dev/sda'
```

**Comment by Wiebelt** [comment]
When i set the start_part_size to 1 it works :-)

**Comment by karasu** [comment]
Thanks for your findings!
