### ISSUE TITLE
Cnchi 0.10.5 even fails on automatic install

### ISSUE THREAD

**Issue by nanotux** [Antergos/Cnchi#376]
1. Booting antergos-2015.08.18-x86_64
2. Choosing "Whole Disk"
3. Cnchi fails ...

<pre><code>
[2015-08-19 15:29:44] [cnchi] INFO: Also sending Cnchi log messages to bugsnag server (using python-bugsnag).
[2015-08-19 15:29:44] [cnchi] INFO: Using GTK v3.16.6
[2015-08-19 15:29:44] [cnchi] INFO: Verwende pyalpm v0.7 als Schnittstelle zu libalpm v9.0.1
[2015-08-19 15:29:44] [main_window] INFO: Cnchi Installationsprogramm Version 0.10.5
.
.
.
[2015-08-19 15:31:33] [ask] DEBUG: Alle externen Prozesse sind abgeschlossen. Installation kann forgesetzt werden
[2015-08-19 15:31:34] [automatic] DEBUG: ATA ST320LT007-9ZV14 [320 GB] (/dev/sda)
[2015-08-19 15:31:34] [automatic] DEBUG: Intenso Rainbow Line [3 GB] (/dev/sdb)
[2015-08-19 15:32:08] [automatic] INFO: Automatische Installation auf /dev/sda
[2015-08-19 15:32:08] [automatic] INFO: Cnchi installiert Antergos auf /dev/sda
[2015-08-19 15:32:08] [automatic] INFO: Antergos wird den Bootloader grub2 auf Gerät ‚/dev/sda‘ installieren
[2015-08-19 15:32:08] [process] DEBUG: Erstelle Partitionen und zugehörige Dateisysteme in /dev/sda
[2015-08-19 15:32:08] [auto_partition] DEBUG: Gesamte Plattengröße: 305245MiB
[2015-08-19 15:32:08] [auto_partition] DEBUG: Größe der Bootpartition: 256MiB
[2015-08-19 15:32:08] [auto_partition] DEBUG: Swap-Partitionsgröße: 7903MiB
[2015-08-19 15:32:08] [auto_partition] DEBUG: Root-Partitionsgröße: 30000MiB
[2015-08-19 15:32:08] [auto_partition] DEBUG: Home-Partitionsgröße: 267085MiB
[2015-08-19 15:32:09] [auto_partition] WARNING: Kann Dateisystem von Gerät /dev/sda nicht säubern
[2015-08-19 15:32:09] [auto_partition] WARNING: Befehl ['wipefs', '-a', '/dev/sda'] fehlgeschlagen
[2015-08-19 15:32:09] [auto_partition] WARNING: Ausgabe: None
[2015-08-19 15:32:11] [auto_partition] ERROR: Fehler beim Erstellen einer neuen Partitionstabelle auf Gerät /dev/sda
[2015-08-19 15:32:11] [auto_partition] ERROR: Befehl ['parted', '--align', 'optimal', '--script', '/dev/sda', 'mktable', 'msdos'] fehlgeschlagen
[2015-08-19 15:32:11] [auto_partition] ERROR: Ausgabe: None
[2015-08-19 15:32:11] [process] ERROR: 'Fehler beim Erstellen einer neuen Partitionstabelle auf Gerät /dev/sda'
[2015-08-19 15:32:11] [process] ERROR: Traceback (most recent call last):

[2015-08-19 15:32:11] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 307, in parted_mktable
    subprocess.check_call(cmd)

[2015-08-19 15:32:11] [process] ERROR:   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)

[2015-08-19 15:32:11] [process] ERROR: subprocess.CalledProcessError: Command '['parted', '--align', 'optimal', '--script', '/dev/sda', 'mktable', 'msdos']' returned non-zero exit status 1

[2015-08-19 15:32:11] [process] ERROR: 
During handling of the above exception, another exception occurred:

[2015-08-19 15:32:11] [process] ERROR: Traceback (most recent call last):

[2015-08-19 15:32:11] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/process.py", line 176, in run
    self.run_installation()

[2015-08-19 15:32:11] [process] ERROR:   File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)

[2015-08-19 15:32:11] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/process.py", line 240, in run_installation
    auto.run()

[2015-08-19 15:32:11] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 726, in run
    parted_mktable(device, "msdos")

[2015-08-19 15:32:11] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 313, in parted_mktable
    raise InstallError(txt)

[2015-08-19 15:32:11] [process] ERROR: misc.misc.InstallError: 'Fehler beim Erstellen einer neuen Partitionstabelle auf Gerät /dev/sda'

[2015-08-19 15:32:41] [slides] INFO: Installiere mittels der ‚automatic‘-Methode
[2015-08-19 15:32:41] [show_message] ERROR: 'Fehler beim Erstellen einer neuen Partitionstabelle auf Gerät /dev/sda'
</code></pre>

**Comment by nanotux** [comment]
1. Booting same ISO
2. Cnchi updates to 0.10.7
3. Installation is successful (choosing "whole disk")
