### ISSUE TITLE
After a mirror timeout cnchi does not try another one, it simply fails

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#410]
http://forum.antergos.com/topic/2828/installation-failing-at-different-phases

```
2015-09-07 08:05:36 [ERROR] process.py(106) run(): HTTPConnectionPool(host='mirror.fluxent.de', port=80): Read timed out.
2015-09-07 08:05:36 [ERROR] process.py(110) run(): Traceback (most recent call last):
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
2015-09-07 08:05:36 [ERROR] process.py(110) run(): socket.timeout: timed out
2015-09-07 08:05:36 [ERROR] process.py(110) run(): 
During handling of the above exception, another exception occurred:
2015-09-07 08:05:36 [ERROR] process.py(110) run(): Traceback (most recent call last):
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/site-packages/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 258, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
2015-09-07 08:05:36 [ERROR] process.py(110) run(): requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='mirror.fluxent.de', port=80): Read timed out.
2015-09-07 08:05:36 [ERROR] process.py(110) run(): 
During handling of the above exception, another exception occurred:
2015-09-07 08:05:36 [ERROR] process.py(110) run(): Traceback (most recent call last):
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 89, in run
    self.install_screen.run_install(pkg.packages, down.metalinks)
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/advanced.py", line 2219, in run_install
    self.installation.start()
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 277, in start
    self.download_packages()
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 332, in download_packages
    download_packages.start(self.metalinks)
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/download/download.py", line 136, in start
    if not download.start(self.metalinks):
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/download/download_requests.py", line 186, in start
    for data in r.iter_content(1024):
2015-09-07 08:05:36 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/site-packages/requests/models.py", line 680, in generate
    raise ConnectionError(e)
2015-09-07 08:05:36 [ERROR] process.py(110) run(): requests.exceptions.ConnectionError: HTTPConnectionPool(host='mirror.fluxent.de', port=80): Read timed out.
```

**Comment by karasu** [comment]
Fixed here: https://github.com/lots0logs/cnchi-dev/commit/35f6553d97ee3a5345177640120fcfe45caf1cef
