### ISSUE TITLE
transient_for attribute not a GtkWindow

### ISSUE THREAD

**Issue by ial0** [Antergos/Cnchi#417]
When trying to show message dialogs, I found cnchi was crashing with, transient_for attribute not a GtkWindow type errors, a particular example would be show.question() and line 1906 in advance.py

Using ISO 08-09-15 i686

**Comment by karasu** [comment]
@ial0 : Do you have an easy way to reproduce this? I can't reproduce it here (all question messages when using advanced are shown correctly).

**Comment by ial0** [comment]
Using 0.12.12 on i686, go through an advance setup. The partition I selected for /boot is currently mounted
/run/media/antergos/f3d9c6fe-9713-4bd7-98e4-eaf96a3fa155
/ (root) is not mounted.

When trying to continue,

Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/main_window.py", line 412, in on_forward_button_clicked
    self.current_page.prepare('forwards')
  File "/usr/share/cnchi/cnchi/summary.py", line 150, in prepare
    self.translate_ui()
  File "/usr/share/cnchi/cnchi/summary.py", line 132, in translate_ui
    changes = install_screen.get_changes()
  File "/usr/share/cnchi/cnchi/installation/advanced.py", line 1906, in get_changes
    response = show.question(self.get_toplevel(), msg)
  File "/usr/share/cnchi/cnchi/show_message.py", line 98, in question
    text=_("Antergos Installer - Confirmation"))
  File "/usr/lib/python3.4/site-packages/gi/overrides/__init__.py", line 313, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py", line 537, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python3.4/site-packages/gi/overrides/__init__.py", line 313, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3.4/site-packages/gi/overrides/__init__.py", line 313, in new_init
    return super_init_func(self, **new_kwargs)
TypeError: could not convert value for property `transient_for' from InstallationAdvanced to GtkWindow
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/main_window.py", line 401, in on_forward_button_clicked
    stored = self.current_page.store_values()
  File "/usr/share/cnchi/cnchi/summary.py", line 167, in store_values
    _("Are you REALLY sure you want to continue?"))
  File "/usr/share/cnchi/cnchi/show_message.py", line 98, in question
    text=_("Antergos Installer - Confirmation"))
  File "/usr/lib/python3.4/site-packages/gi/overrides/__init__.py", line 313, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py", line 537, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python3.4/site-packages/gi/overrides/__init__.py", line 313, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3.4/site-packages/gi/overrides/__init__.py", line 313, in new_init
    return super_init_func(self, **new_kwargs)
TypeError: could not convert value for property `transient_for' from Summary to GtkWindow
2015-09-14 16:50:08 [INFO] main_window.py(369) on_exit_button_clicked(): Quiting installer...

is the error caught

**Comment by karasu** [comment]
Thanks! That's something I can work with.

**Comment by karasu** [comment]
Fixed and tested in 0.13.40
