### ISSUE TITLE
Can't convert 'bool' object to str implicitly

### ISSUE THREAD

**Issue by wywialm** [Antergos/Cnchi#436]
This error appears each time during installation:

![screenshot from 2015-09-27 02-27-19](https://cloud.githubusercontent.com/assets/3671764/10118904/411a3d2e-6475-11e5-8244-7694daf731da.png)

How can I additionally debug this?

**Comment by karasu** [comment]
@wywialm : It's nearly impossible to know what's wrong if you don't provide a log file. It's in /tmp/cnchi.log

Please, it would be most helpful.

**Comment by fionera** [comment]
I will try in the next hours to replicate this...

**Comment by wywialm** [comment]
These are the logs beginning from he end of the package installation process. I had to put only part of the logs as they are too long to be pasted here in full. I will try to provide rest if necessary

--------------------------------------

2015-09-27 02:26:33 [INFO] slides.py(224) manage_events_from_cb_queue(): Installing mesa-vdpau (843/843)
2015-09-27 02:26:33 [INFO] slides.py(224) manage_events_from_cb_queue(): Configuring your new system
2015-09-27 02:26:33 [DEBUG] install.py(1030) configure_system(): User user added.
2015-09-27 02:26:33 [DEBUG] chroot.py(136) run(): Changing finger information for user.

Finger information changed.
2015-09-27 02:26:33 [DEBUG] install.py(1045) configure_system(): Hostname set to localhost
2015-09-27 02:26:33 [DEBUG] install.py(1049) configure_system(): Set the same password to root.
2015-09-27 02:26:34 [INFO] slides.py(224) manage_events_from_cb_queue(): Generating locales...
2015-09-27 02:26:34 [DEBUG] chroot.py(136) run(): Generating locales...
  en_US.UTF-8... done
  en_US.UTF-8... done
Generation complete.
2015-09-27 02:26:35 [INFO] slides.py(224) manage_events_from_cb_queue(): Adjusting hardware clock...
2015-09-27 02:26:36 [DEBUG] install.py(1075) configure_system(): Set /etc/X11/xorg.conf.d/00-keyboard.conf for the xkblayout
2015-09-27 02:26:36 [DEBUG] install.py(1092) configure_system(): 00-keyboard.conf written.
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): ‘/etc/skel/./.bashrc’ -> ‘/root/./.bashrc’
‘/etc/skel/./.bash_profile’ -> ‘/root/./.bash_profile’
‘/etc/skel/./.bash_logout’ -> ‘/root/./.bash_logout’
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Master',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Front',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Center',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'LFE',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Headphone',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Speaker',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'PCM',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Line',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'External',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'FM',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Master',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Master',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Analog',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Aux',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Aux2',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'PCM',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'PCM',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'PCM',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'PCM',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'PCM',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Playback',0
2015-09-27 02:26:36 [INFO] slides.py(224) manage_events_from_cb_queue(): Configuring keymap...
2015-09-27 02:26:36 [INFO] slides.py(224) manage_events_from_cb_queue(): Configuring hardware...
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'PCM',1
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'DAC',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'DAC',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'DAC',1
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Synth',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'CD',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Wave',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Music',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'AC97',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Analog',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'VIA',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'VIA',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'VIA',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'VIA',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Mic',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Master',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Master',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'SB',0
2015-09-27 02:26:36 [DEBUG] chroot.py(136) run(): amixer: Unable to find simple control 'Audigy',0
2015-09-27 02:26:36 [DEBUG] install.py(1124) configure_system(): Updated Alsa mixer settings
2015-09-27 02:26:36 [DEBUG] install.py(1132) configure_system(): Updated fluidsynth configuration file
2015-09-27 02:26:36 [DEBUG] mkinitcpio.py(106) set_hooks_and_modules(): Setting hooks and modules in mkinitcpio.conf
2015-09-27 02:26:36 [DEBUG] mkinitcpio.py(107) set_hooks_and_modules(): HOOKS="base udev autodetect modconf block keyboard keymap encrypt lvm2 resume filesystems fsck"
2015-09-27 02:26:36 [DEBUG] mkinitcpio.py(108) set_hooks_and_modules(): MODULES="dm_mod dm_crypt ext4 aes_x86_64 sha256 sha512"
2015-09-27 02:26:37 [INFO] slides.py(224) manage_events_from_cb_queue(): Configuring System Startup...
2015-09-27 02:26:47 [DEBUG] chroot.py(136) run(): ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
==> Starting build: 4.1.6-1-ARCH
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [encrypt]
  -> Running build hook: [lvm2]
  -> Running build hook: [resume]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux.img
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
==> Starting build: 4.1.6-1-ARCH
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: wd719x
==> WARNING: Possibly missing firmware for module: aic94xx
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [encrypt]
  -> Running build hook: [lvm2]
  -> Running build hook: [resume]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-fallback.img
==> Image generation successful
2015-09-27 02:26:47 [DEBUG] install.py(1141) configure_system(): Running Cnchi post-install script
2015-09-27 02:26:47 [ERROR] process.py(106) run(): Can't convert 'bool' object to str implicitly
2015-09-27 02:26:47 [ERROR] process.py(110) run(): Traceback (most recent call last):
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 89, in run
    self.install_screen.run_install(pkg.packages, down.metalinks)
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/automatic.py", line 366, in run_install
    self.installation.start()
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 283, in start
    self.configure_system()
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 1154, in configure_system
    subprocess.check_call(cmd, timeout=300)
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
2015-09-27 02:26:47 [ERROR] process.py(110) run():   File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
2015-09-27 02:26:47 [ERROR] process.py(110) run(): TypeError: Can't convert 'bool' object to str implicitly

**Comment by AnthonyWatson** [comment]
Just wanted to add that I'm also experiencing this issue, and here is a link to a related issue thread from the Antergos page:

http://forum.antergos.com/topic/2940/can-t-convert-bool-object-to-str-implicitly

**Comment by fionera** [comment]
I think its this: 

        if keyboard_variant:
            cmd.append(keyboard_variant)
        else:
            cmd.append("")
        cmd.append(self.vbox)

in install.py at 1148

**Comment by ShapeShifter499** [comment]
I had this issue yesterday, the new cnchi 0.12.24 seems to have this fixed. Thank you guys

**Comment by AnthonyWatson** [comment]
Tried installing Antergos last night and Cnchi 0.12.24 fixed the issue; thanks for the prompt fix everyone! :)
