### ISSUE TITLE
checksum issue installing antergos-2015.11.14-x86_64.iso - cinnamon

### ISSUE THREAD

**Issue by kialam** [Antergos/Cnchi#482]
```shell
2015-12-03 08:40:39 [DEBUG] pac.py(506) cb_log(): sha256sum: 714e4444e7195467e4db0462ad1b19ea10435762cb3534033b805186ad2cf75b
2015-12-03 08:40:39 [DEBUG] pac.py(506) cb_log(): checking sha256sum for /install/var/cache/pacman/pkg/antergos-keyring-20150806-1-any.pkg.tar.xz
2015-12-03 08:40:39 [DEBUG] pac.py(504) cb_log(): returning error 33 from check_validity : invalid or corrupted package
2015-12-03 08:40:39 [ERROR] pac.py(161) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 33 (invalid or corrupted package), []
2015-12-03 08:40:39 [DEBUG] pac.py(164) finalize_transaction(): Releasing alpm transaction...
2015-12-03 08:40:39 [DEBUG] pac.py(166) finalize_transaction(): Alpm transaction done.
2015-12-03 08:40:39 [ERROR] process.py(106) run(): "Can't install necessary packages. Cnchi can't continue."
2015-12-03 08:40:39 [ERROR] process.py(110) run(): Traceback (most recent call last):
2015-12-03 08:40:39 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 89, in run
    self.install_screen.run_install(pkg.packages, down.metalinks)
2015-12-03 08:40:39 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/automatic.py", line 366, in run_install
    self.installation.start()
2015-12-03 08:40:39 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)
2015-12-03 08:40:39 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 280, in start
    self.install_packages()
2015-12-03 08:40:39 [ERROR] process.py(110) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 416, in install_packages
    raise InstallError(txt)
2015-12-03 08:40:39 [ERROR] process.py(110) run(): misc.misc.InstallError: "Can't install necessary packages. Cnchi can't continue."
```

**Comment by kialam** [comment]
Ran installer again and everything worked fine, checksums passed. Closing ticket.
