### ISSUE TITLE
Antergos installation on ZFS failed

### ISSUE THREAD

**Issue by satriani-vai** [Antergos/Cnchi#524]
`"Error running ['zfs', 'create', '-V', '-7072G', '-b', '4096', '-o', 'primarycache=metadata', '-o', 'checksum=off', '-o', 'com.sun:auto-snapshot=false', 'antergos_wzpp/home']: bad volume size '-7072G': bad numeric value '-7072G'"`

**Comment by karasu** [comment]
Obviously, first one is a bad calculation. Can you tell me how big is your harddrive?

Second one is because you didn't reboot your computer before retrying, right?

**Comment by satriani-vai** [comment]
I have a 1TB hybrid harddrive

**Comment by lots0logs** [comment]
@karasu I don't have time to do it now so if you can get to it before me then feel free... Let's create this file after we've finished formatting/partitioning: `/var/tmp/.cnchi_partitioning_completed`. We can check for the existence of the file in check.py and prevent installation from continuing (eg. require a reboot)

**Comment by satriani-vai** [comment]
this issue is still outstanding
[http://i.imgur.com/KLQB1va.png](url)

**Comment by lots0logs** [comment]
@satriani-vai I performed two successful ZFS installations yesterday. Could you provide your logs for your failed attempts please?

**Comment by satriani-vai** [comment]
Of course the last testing ISO should do the trick.
Could you please send me a link to the ISO please?

**Comment by lots0logs** [comment]
Sure! build.antergos.com/browse/testing

**Comment by satriani-vai** [comment]
Won't boot :(
I will try tomorrow's build.

**Comment by satriani-vai** [comment]
OK I've got it with another USB stick, but this issue is still outstanding with latest testing ISO
Here the output:

```
...
2016-02-08 13:18:31 [INFO] pac.py(530) cb_log(): adding 'fakeroot' to package cache for db 'local'
2016-02-08 13:18:31 [DEBUG] pac.py(528) cb_log(): added 837 packages to package cache for db 'local'
2016-02-08 13:18:31 [DEBUG] pac.py(528) cb_log(): loading group cache for repository 'community'
2016-02-08 13:18:48 [DEBUG] zfs.py(639) run_format(): Configuring ZFS in /dev/sda
2016-02-08 13:18:48 [DEBUG] zfs.py(585) init_device(): Zapping device /dev/sda...
2016-02-08 13:18:49 [INFO] slides.py(242) manage_events_from_cb_queue(): 
2016-02-08 13:18:49 [INFO] slides.py(242) manage_events_from_cb_queue(): Getting your disk(s) ready for Antergos...
2016-02-08 13:18:50 [DEBUG] run_cmd.py(70) call(): 1953525168
2016-02-08 13:18:51 [DEBUG] run_cmd.py(70) call(): no pools available to import
2016-02-08 13:18:51 [DEBUG] run_cmd.py(70) call(): no pools available to import
2016-02-08 13:18:56 [DEBUG] zfs.py(1000) create_zfs(): Cnchi will create a ZFS pool using /dev/sda3 devices
2016-02-08 13:18:56 [DEBUG] zfs.py(933) create_zfs_pool(): Creating zfs pool antergos_hom2 of type none
2016-02-08 13:18:56 [DEBUG] zfs.py(957) create_zfs_pool(): Pool antergos_hom2 created.
2016-02-08 13:18:56 [WARNING] zfs.py(869) set_zfs_mountpoint(): cannot mount '/': directory is not empty
property may be set but unable to remount filesystem
2016-02-08 13:18:56 [DEBUG] zfs.py(778) get_pool_size(): zpool list -H -o size antergos_hom2
2016-02-08 13:18:56 [DEBUG] zfs.py(1042) create_zfs(): Creating zfs subvolume 'home' (899GB)
2016-02-08 13:18:56 [DEBUG] zfs.py(850) create_zfs_vol(): Creating a zfs vol antergos_hom2/home of size 899GB
2016-02-08 13:18:56 [ERROR] run_cmd.py(85) call(): Error running ['zfs', 'create', '-V', '899G', '-b', '4096', '-o', 'primarycache=metadata', '-o', 'checksum=off', '-o', 'com.sun:auto-snapshot=false', 'antergos_hom2/home']: cannot create 'antergos_hom2/home': out of space
2016-02-08 13:18:57 [ERROR] process.py(129) run(): "Error running ['zfs', 'create', '-V', '899G', '-b', '4096', '-o', 'primarycache=metadata', '-o', 'checksum=off', '-o', 'com.sun:auto-snapshot=false', 'antergos_hom2/home']: cannot create 'antergos_hom2/home': out of space"
2016-02-08 13:18:57 [ERROR] process.py(133) run(): Traceback (most recent call last):
2016-02-08 13:18:57 [ERROR] process.py(133) run():   File "/home/antergos/Downloads/Cnchi/cnchi/misc/run_cmd.py", line 66, in call
    timeout=timeout)
2016-02-08 13:18:57 [ERROR] process.py(133) run():   File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
2016-02-08 13:18:57 [ERROR] process.py(133) run():   File "/usr/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
2016-02-08 13:18:57 [ERROR] process.py(133) run(): subprocess.CalledProcessError: Command '['zfs', 'create', '-V', '899G', '-b', '4096', '-o', 'primarycache=metadata', '-o', 'checksum=off', '-o', 'com.sun:auto-snapshot=false', 'antergos_hom2/home']' returned non-zero exit status 1
2016-02-08 13:18:57 [ERROR] process.py(133) run(): 
During handling of the above exception, another exception occurred:
2016-02-08 13:18:58 [ERROR] process.py(133) run(): Traceback (most recent call last):
2016-02-08 13:18:58 [ERROR] process.py(133) run():   File "/home/antergos/Downloads/Cnchi/cnchi/installation/process.py", line 98, in run
    self.install_screen.run_format()
2016-02-08 13:18:58 [ERROR] process.py(133) run():   File "/home/antergos/Downloads/Cnchi/cnchi/installation/zfs.py", line 746, in run_format
    self.create_zfs(solaris_partition_number)
2016-02-08 13:18:58 [ERROR] process.py(133) run():   File "/home/antergos/Downloads/Cnchi/cnchi/installation/zfs.py", line 1043, in create_zfs
    self.create_zfs_vol(pool_name, "home", home_size)
2016-02-08 13:18:58 [ERROR] process.py(133) run():   File "/home/antergos/Downloads/Cnchi/cnchi/installation/zfs.py", line 859, in create_zfs_vol
    call(cmd, fatal=True)
2016-02-08 13:18:58 [ERROR] process.py(133) run():   File "/home/antergos/Downloads/Cnchi/cnchi/misc/run_cmd.py", line 87, in call
    raise InstallError(msg)
2016-02-08 13:18:58 [ERROR] process.py(133) run(): misc.extra.InstallError: "Error running ['zfs', 'create', '-V', '899G', '-b', '4096', '-o', 'primarycache=metadata', '-o', 'checksum=off', '-o', 'com.sun:auto-snapshot=false', 'antergos_hom2/home']: cannot create 'antergos_hom2/home': out of space"
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
2016-02-08 13:18:59 [INFO] connectionpool.py(207) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2016-02-08 13:18:59 [DEBUG] connectionpool.py(386) _make_request(): "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=6843&result=False HTTP/1.1" 200 None
python3: no process found
```

**Comment by lots0logs** [comment]
@satriani-vai If you have time could you test the latest ISO with latest `cnchi-dev` package? I think I identified and fixed the issue. I was able to make two successful zfs installs earlier today.

**Comment by satriani-vai** [comment]
https://github.com/Antergos/Cnchi/issues/536

**Comment by satriani-vai** [comment]
Alright, finally it works without different home partition/volume.
It's very simple `sudo zfs create -p antergos_{whatever}/home`
When the time comes with ZFS + LUKS? :)

**Comment by karasu** [comment]
I think that the best would be to not tell zfs a predefined home size. I'll change it asap.

**Comment by satriani-vai** [comment]
I absolutely agree with you. That's the nice thing about ZFS. You don't need to define a dataset size. I love ZFS, I working about many years with ZFS on FreeBSD and have very good experience.
I'm very happy, you have chosen this nice filesystem for Antergos. This makes Antergos even more interesting ;)

**Comment by nitrogensky** [comment]
Installed on a 30G VM and it set the ZFS Pool to 29.5G, but `sudo zpool status` and `sudo zpool iostat -v` show all is well. No errors or warnings.

**Comment by karasu** [comment]
@nitrogensky : If you can, could you post here a `zpool status` and a `zfs list` ?

**Comment by nitrogensky** [comment]
@karasu 
[zpool status.txt](https://github.com/Antergos/Cnchi/files/128608/zpool.status.txt)
[zfs list.txt](https://github.com/Antergos/Cnchi/files/128609/zfs.list.txt)

I don't know what I am doing wrong, but I couldn't get the output to format corectly, so I hope these files are OK.

**Comment by karasu** [comment]
@nitrogensky : To avoid problems when booting, Cnchi creates a specific /boot partition with ext4. I'm not really sure this is necessary with the latest Grub2, though. That's why you get a 29,5GB pool, because 512MB are used by /boot

**Comment by karasu** [comment]
For future reference: https://github.com/Antergos/Cnchi/commit/d0e393b7cb64c8b2d1919191237a18479b0d3ff4

**Comment by itys** [comment]
This appears to continue to be an issue when installing ZFS over an existing partition scheme. 

Current error number 236168, from antergos-18.1-x86_64.iso, Cnchi version 0.14.410 identified by the installer-update as current. 
"error wipefs probing initialization failed"
"Cannot wipe the filesystem of device /dev/sda"

Effective workaround/fix is to reboot and restart the install. 

As this has been open for a couple years, perhaps amend the error message to include "Please try again.. no, seriously, it'll probably work the second time." ? :-)

**Comment by mrcasquinhas** [comment]
"'Cannot wipe the filesystem of device /dev/sda:wipefs: error /dev/sda: probing initialization failed: Device or resource busy'
Please reference the following number when reporting this error: 965490"

This is the error that I got when choosing ZFS. So I started gparted, removed the 'unknown' partition and it is now unallocated. It told me to reboot, so I did.
Installed again, with ZFS option and GPT, not MBR. All other options are at defaults.
It works now, it's installing but it should go to the end without anymore issues. So the problem was partition was 'crazy' and unknow, so ZFS did not like it.
