### ISSUE TITLE
stuck on Getting your disk(s) ready for Antergos at 100%

### ISSUE THREAD

**Issue by femans** [Antergos/Cnchi#543]
Cnchi 0.14 hangs on my system at "Getting your disk(s) ready for Antergos" at 100%;

I followed the installer in a few different combinations, it kept hanging. Then I started it from command line to see if some output popped up; and there was: bunch of errors. An undefined variable in a function call. 

this is the terminal output: http://paste2.org/A7hOjGM9

this is the chchi.log file: http://paste2.org/0w9Ak4dG mentioning another error, it cant unmount /install, because no such mountpoint.

Pity it didnt show up in the frontend there was something wrong! I sat there waiting like a goose for 3 times until i started suspecting maybe something was wrong.

My system is a thinkpad t440s with a 500GB SSD in it, but I don't think it has anything to do with my system.
I did automated install because I dont want to figure out how to partition my disk; too much work. In stead I will try to see if I can manually fix the bug (s).

**Comment by femans** [comment]
I solved my personal issue, of not being able to install, by downgrading to Cnchi to version 0.12.46-1
Seems like a little bug made it into the release...

Nonetheless good work making an easy to use arch installer. This can make a tremendous difference in adoption of arch. 

Besides that, would it be possible to make cnchi remember settings, at least when going back one step? Preferably also when it crashes? I've had to do the same settings I think something like 10 times today.

**Comment by karasu** [comment]
Thanks for your patience and testings. Thanks to your logs it was pretty easy to find the bug.

About remember settings, it should remember even if you go back, so there must be some bug there (we'll check it asap). About loading/storing them, I'll add it to our big TODO list.

Thanks again!

**Comment by femans** [comment]
you are welcome, glad i could help. btw in the 0.12 version the settings were remembered when going hence and forth.

**Comment by oddant** [comment]
help, i have the same issue, stuck at 100% "getting your disk(s) ready for Antergos"... Could someone tell me how to downgrade cnchi as femans did ? i am not a linux pro..

**Comment by karasu** [comment]
@oddant this is a very old issue, I'm positive you're having another problem. Anyway, can you post your log? (/tmp/cnchi.log) (you can use paste2.org)

Thanks!

**Comment by MinaMaged** [comment]
I'm also having the same problem

**Comment by karasu** [comment]
@MinaMaged can you post your log? (/tmp/cnchi.log)

**Comment by mproffitt** [comment]
This error can be reproduced when a previous LVM installation has failed. Attempting to restart the installation then triggers a ValueError trying to remove a non-existent LVM configuration.

```
2017-02-02 17:45:23 [DEBUG] run_cmd.py(104) call():   WARNING: Device for PV lOODnA-rqNE-WHMT-orKD-kYoJ-j3cr-jwA1iO not found or rejected by a filter.
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/share/cnchi/cnchi/installation/process.py", line 97, in run
    self.install_screen.run_format()
  File "/usr/share/cnchi/cnchi/installation/automatic.py", line 318, in run_format
    auto.run()
  File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 621, in run
    remove_lvm(device)
  File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 152, in remove_lvm
    (lvolume, vgroup, ldevice) = lvolume.split()
ValueError: too many values to unpack (expected 3)
2017-02-02 17:45:24 [INFO] slides.py(268) manage_events_from_cb_queue(): 
2017-02-02 17:45:24 [INFO] slides.py(268) manage_events_from_cb_queue(): Getting your disk(s) ready for Antergos...
```

At this point, Cnchi will hang indefinitely and the only way to install is by running manual partitioning.

**Comment by elixir75** [comment]
I'm having the same problem when installing to existing LVM partitions. I have separate /boot, /root, and /home - all are lvm2 logical volumes set up prior to using the antergos installer (via a working Ubuntu 17.04 system on separate logical volumes in the same volume group/pv. 

I'm using the latest iso written to a usb.

Here's my log: https://paste2.org/4hBNEvyZ

**Comment by GeorgeTG** [comment]
`2017-08-18 19:42:28 [DEBUG] run_cmd.py(104) call():   root   kubuntu-vg /dev/mapper/luks-2683ff97-716e-414f-a363-fb2200273ac5(0)    
  swap_1 kubuntu-vg /dev/mapper/luks-2683ff97-716e-414f-a363-fb2200273ac5(24291)
2017-08-18 19:42:28 [DEBUG] run_cmd.py(104) call():   kubuntu-vg /dev/mapper/luks-2683ff97-716e-414f-a363-fb2200273ac5(0)    
  kubuntu-vg /dev/mapper/luks-2683ff97-716e-414f-a363-fb2200273ac5(24291)
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/share/cnchi/cnchi/installation/process.py", line 97, in run
    self.install_screen.run_format()
  File "/usr/share/cnchi/cnchi/installation/automatic.py", line 318, in run_format
    auto.run()
  File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 622, in run
    remove_lvm(device)
  File "/usr/share/cnchi/cnchi/installation/auto_partition.py", line 163, in remove_lvm
    (vgname, vgdevice) = vgname.split()
`
Here's how it fails on my system, doesn't report any error on the GUI.
Unfortunately I removed the virtual groups by hand before testing the exact command that is ran through the code.
For everyone that has the same problem try
https://wiki.archlinux.org/index.php/LVM#Remove_logical_volume
Then restart the installer.

**Comment by maxrousseau** [comment]
I had the same issue and resolved it by simply closing the Cnchi window that appeared upon boot, letting the update run then re-launching it again to proceed with the installation. 

Hope this helps
