### ISSUE TITLE
cnchi + XFS doesn't work

### ISSUE THREAD

**Issue by xdajog** [Antergos/Cnchi#550]
### Problem:
cnchi cannot handle existing LVM partitions with XFS

### Steps To Reproduce:
1. create a logical volume and format as XFS
2. start cnchi and choose manual partition layout
3. But the next screen is blank and should normally let me choose my manual partitions I could skip to the next screen but that would mean to skip where antergos should be installed…
For this please see “cnchni_BASE.log”
The reason why that may happens seems to be clear in this case:
cnchi tries to get information from my LVM partitions with the wrong command! It states “command … btrfs … non-zero exit status…” Well that indeed cannot work as those partitions are all XFS - not btrfs as you can see in the cnchni_BASE.log.

### Log Files
http://s000.tinyupload.com/download.php?file_id=02020685443536475473

Content of **logs.tgz**:
- can be **ignored** (they are for another bug report)

Content of **logs2.tgz**:
- cnchi.log_BASE --> the chnchi.log when selecting NO desktop so “Base” only
- cnchi_BASE.log --> the output from the terminal where I executed “sudo cnchi” and choosing the “base” install

### Additional Notes:
See my post: https://forum.antergos.com/topic/4028/no-installation-possible-cnchi-and-cli for more details

**Comment by karasu** [comment]
[logs2.zip](https://github.com/Antergos/Cnchi/files/148830/logs2.zip)

**Comment by karasu** [comment]
```
2016-02-26 10:10:47 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/mapper/vg_ssd-ubuntu']: b''
ERROR: no btrfs on /dev/dm-4
** [Bugsnag] No API key configured, couldn't notify
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/parted3/used_space.py", line 183, in get_used_btrfs
    result = subprocess.check_output(["btrfs", "filesystem", "show", part])
  File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['btrfs', 'filesystem', 'show', '/dev/mapper/vg_ssd-ubuntu']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/main_window.py", line 435, in on_forward_button_clicked
    self.current_page.prepare('forwards')
  File "/usr/share/cnchi/cnchi/installation/advanced.py", line 1651, in prepare
    self.update_view()
  File "/usr/share/cnchi/cnchi/installation/advanced.py", line 917, in update_view
    self.fill_partition_list()
  File "/usr/share/cnchi/cnchi/installation/advanced.py", line 545, in fill_partition_list
    elif used_space.is_btrfs(partition_path):
  File "/usr/share/cnchi/cnchi/parted3/used_space.py", line 255, in is_btrfs
    space = get_used_btrfs(part)
  File "/usr/share/cnchi/cnchi/misc/extra.py", line 191, in helper
    return func(*args, **kwargs)
  File "/usr/share/cnchi/cnchi/parted3/used_space.py", line 186, in get_used_btrfs
    logging.error("Can't detect used space of BTRFS partition %s: %s", part, err)
NameError: name 'err' is not defined
```

**Comment by dmarku** [comment]
Hello,

I tried installing Antergos yesterday and also had a blank page after choosing manual partitioning. While my setup is a little bit different, I believe the problem is at least closely related to this, so I didn't create another issue.

The problem was caused by a LVM volume group with partitions on one of my drives. Deleting the logical volumes fixed it: after that, the installer was showing the remaining drives and their partitions. Creating a logical volume again made the bug appear again (there was no filesystem present at that point).

I'm using Antergos Live 64-bit, the image is __antergos-2016.02.21-x86_64.iso__.

Cnchi is in version 0.14.62:
```
[antergos@ant-16 ~]$ cnchi --version
Cnchi (Antergos Setup) Version 0.14.62
```

## Cnchi terminal output

I ran Cnchi from the terminal with `sudo cnchi` and the terminal output ended with the following, after debug messages about locale, keyboard and package selection and mirror ranking:

```
2016-03-08 17:08:03 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/mapper/linux--vg-antergos-home']: b''
** [Bugsnag] No API key configured, couldn't notify
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/parted3/used_space.py", line 183, in get_used_btrfs
    result = subprocess.check_output(["btrfs", "filesystem", "show", part])
  File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['btrfs', 'filesystem', 'show', '/dev/mapper/linux--vg-antergos-home']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/main_window.py", line 435, in on_forward_button_clicked
    self.current_page.prepare('forwards')
  File "/usr/share/cnchi/cnchi/installation/advanced.py", line 1651, in prepare
    self.update_view()
  File "/usr/share/cnchi/cnchi/installation/advanced.py", line 917, in update_view
    self.fill_partition_list()
  File "/usr/share/cnchi/cnchi/installation/advanced.py", line 545, in fill_partition_list
    elif used_space.is_btrfs(partition_path):
  File "/usr/share/cnchi/cnchi/parted3/used_space.py", line 255, in is_btrfs
    space = get_used_btrfs(part)
  File "/usr/share/cnchi/cnchi/misc/extra.py", line 191, in helper
    return func(*args, **kwargs)
  File "/usr/share/cnchi/cnchi/parted3/used_space.py", line 186, in get_used_btrfs
    logging.error("Can't detect used space of BTRFS partition %s: %s", part, err)
NameError: name 'err' is not defined
```

I hope this helps to locate the problem.

**Comment by dmarku** [comment]
__Update:__ I've just quickly cloned the Cnchi repository and started the setup there with `sudo ./run`. The volume group is shown, including the one logical volume on it. I can edit it, mark it for formatting and set a mount point. Its size isn't displayed, though. I have not run the remaining steps of the installation process.

![cnchi-git](https://cloud.githubusercontent.com/assets/7983516/13606070/bf717f38-e54a-11e5-834d-8f893ab4228d.png)

**Comment by stratus-ss** [comment]
`2016-03-14 13:44:59 [DEBUG] run_cmd.py(70) call(): /dev/sda1: LABEL="AntergosBoot" UUID="a9aa9ac6-8643-4cba-af59-6f0cd0c7881e" TYPE="ext2" PARTUUID="023dc159-01"
2016-03-14 13:44:59 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sda2']: b''
2016-03-14 13:44:59 [WARNING] run_cmd.py(82) call(): Error running ['blkid', '-c', '/dev/null', '/dev/sda2']: 
2016-03-14 13:44:59 [ERROR] run_cmd.py(49) log_exception_info(): Traceback (most recent call last):
2016-03-14 13:44:59 [ERROR] run_cmd.py(49) log_exception_info():   File "/usr/share/cnchi/cnchi/misc/run_cmd.py", line 66, in call
    timeout=timeout)
2016-03-14 13:44:59 [ERROR] run_cmd.py(49) log_exception_info():   File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
2016-03-14 13:44:59 [ERROR] run_cmd.py(49) log_exception_info():   File "/usr/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
2016-03-14 13:44:59 [ERROR] run_cmd.py(49) log_exception_info(): subprocess.CalledProcessError: Command '['blkid', '-c', '/dev/null', '/dev/sda2']' returned non-zero exit status 2
2016-03-14 13:44:59 [WARNING] fs_module.py(85) get_info(): Error running ['blkid', '-c', '/dev/null', '/dev/sda2']: b''
2016-03-14 13:44:59 [DEBUG] fs_module.py(66) get_label(): Can't get partition /dev/sda2 label (or it does not have any)
2016-03-14 13:44:59 [DEBUG] run_cmd.py(70) call(): /dev/sda5: UUID="96ebf733-d055-47a2-910f-845a4ef3e3da" TYPE="xfs" PARTUUID="023dc159-05"
2016-03-14 13:44:59 [DEBUG] fs_module.py(66) get_label(): Can't get partition /dev/sda5 label (or it does not have any)
2016-03-14 13:44:59 [DEBUG] run_cmd.py(70) call(): /dev/sda6: UUID="b96ece1e-7390-4d23-9be0-f0be71169d87" TYPE="swap" PARTUUID="023dc159-06"
2016-03-14 13:44:59 [DEBUG] fs_module.py(66) get_label(): Can't get partition /dev/sda6 label (or it does not have any)`

**Comment by stratus-ss** [comment]
I can confirm this. I created an lvm on sda5 and put swap and an xfs LV. 

Cnchi output:

```
2016-03-14 13:53:29 [DEBUG] run_cmd.py(70) call(): /dev/mapper/antergos-swap: UUID="914d3c37-12d4-42e4-8ec8-b6839c43cbcd" TYPE="swap"
2016-03-14 13:53:29 [DEBUG] fs_module.py(66) get_label(): Can't get partition /dev/mapper/antergos-swap label (or it does not have any)
2016-03-14 13:53:29 [DEBUG] run_cmd.py(70) call(): /dev/mapper/antergos-root: UUID="f0a4a4ad-ab5a-42a3-a1db-1c7305583feb" TYPE="xfs"
2016-03-14 13:53:29 [DEBUG] fs_module.py(66) get_label(): Can't get partition /dev/mapper/antergos-root label (or it does not have any)
dumpe2fs 1.42.13 (17-May-2015)
2016-03-14 13:53:29 [DEBUG] run_cmd.py(70) call(): /dev/sda1: LABEL="AntergosBoot" UUID="a9aa9ac6-8643-4cba-af59-6f0cd0c7881e" TYPE="ext2" PARTUUID="023dc159-01"
2016-03-14 13:53:29 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sda2']: b''
2016-03-14 13:53:29 [WARNING] run_cmd.py(82) call(): Error running ['blkid', '-c', '/dev/null', '/dev/sda2']: 
2016-03-14 13:53:29 [ERROR] run_cmd.py(49) log_exception_info(): Traceback (most recent call last):
2016-03-14 13:53:29 [ERROR] run_cmd.py(49) log_exception_info():   File "/usr/share/cnchi/cnchi/misc/run_cmd.py", line 66, in call
    timeout=timeout)
2016-03-14 13:53:29 [ERROR] run_cmd.py(49) log_exception_info():   File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
2016-03-14 13:53:29 [ERROR] run_cmd.py(49) log_exception_info():   File "/usr/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
2016-03-14 13:53:29 [ERROR] run_cmd.py(49) log_exception_info(): subprocess.CalledProcessError: Command '['blkid', '-c', '/dev/null', '/dev/sda2']' returned non-zero exit status 2
2016-03-14 13:53:29 [WARNING] fs_module.py(85) get_info(): Error running ['blkid', '-c', '/dev/null', '/dev/sda2']: b''
2016-03-14 13:53:29 [DEBUG] fs_module.py(66) get_label(): Can't get partition /dev/sda2 label (or it does not have any)
2016-03-14 13:53:29 [DEBUG] run_cmd.py(70) call(): /dev/sda5: UUID="4KuMv8-dQpT-u3eY-SvdG-r96I-pQdR-44tsqN" TYPE="LVM2_member" PARTUUID="023dc159-05"
2016-03-14 13:53:29 [DEBUG] fs_module.py(66) get_label(): Can't get partition /dev/sda5 label (or it does not have any)
```


![screenshot from 2016-03-14 09-55-35](https://cloud.githubusercontent.com/assets/8162705/13746730/0fd8afda-e9cb-11e5-8b6f-8621f82567e3.png)
