### ISSUE TITLE
DBusException: No such interface '/org/freedesktop/UPower'

### ISSUE THREAD

**Issue by jtojnar** [Antergos/Cnchi#566]
### Problem:
The “System Check” step throws an Exception.

### Steps To Reproduce:
1. Start Cnchi
2. Press “Install It”
3. Press “Next” arrow

### Log Files
Following error is displayed in the terminal:
```
** [Bugsnag] No API key configured, couldn't notify
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/main_window.py", line 435, in on_forward_button_clicked
    self.current_page.prepare('forwards')
  File "/usr/share/cnchi/cnchi/check.py", line 230, in prepare
    self.forward_button.set_sensitive(self.check_all())
  File "/usr/share/cnchi/cnchi/check.py", line 131, in check_all
    on_power = not self.on_battery()
  File "/usr/share/cnchi/cnchi/check.py", line 159, in on_battery
    return misc.get_prop(upower, UPOWER_PATH, 'OnBattery')
  File "/usr/share/cnchi/cnchi/misc/extra.py", line 391, in get_prop
    return obj.Get(iface, prop, dbus_interface=dbus.PROPERTIES_IFACE)
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such interface '/org/freedesktop/UPower'
```
- [/tmp/cnchi.log content](http://paste2.org/HpKHf5V2)

### Additional Notes:
It is a fresh Live CD (2016.02.21).

**Comment by karasu** [comment]
Oh, this has already been fixed. Didn't Cnchi update itself?
Please, test against latest stable version.

**Comment by jtojnar** [comment]
Yes, it seems to work now. It didn’t update last time because I did not have wireless driver.

**Comment by prakal** [comment]
@karasu : I noticed a similar warning in my `cnchi.log` when I tried running the installer recently. I documented the issue in https://github.com/Antergos/Cnchi/issues/851
