### ISSUE TITLE
Cnchi will not start at all

### ISSUE THREAD

**Issue by LiberteCzech** [Antergos/Cnchi#601]
### Problem:
Cnchi will not start at all. Test iso 2016.05.22 and the latest cnchi.

### Steps To Reproduce:
**Run from terminal**

```
[antergos@ant-16 ~]$ sudo cnchi
2016-05-23 03:45:14 [INFO] cnchi.py(283) check_gtk_version(): Using GTK v3.20.5
2016-05-23 03:45:14 [INFO] cnchi.py(295) check_pyalpm_version(): Using pyalpm v0.8 as interface to libalpm v10.0.1
2016-05-23 03:45:14 [DEBUG] cnchi.py(322) check_iso_version(): Running from ISO version 16.5

(cnchi.py:10473): Gtk-WARNING **: Theme parsing error: gtk.css:3978:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
2016-05-23 03:45:15 [INFO] main_window.py(82) __init__(): Cnchi installer version 0.14.72
2016-05-23 03:45:15 [DEBUG] main_window.py(110) __init__(): Cnchi will use '/var/cache/pacman/pkg' as a source for cached xz packages
2016-05-23 03:45:15 [DEBUG] gtkbasebox.py(60) __init__(): Loading 'welcome' screen
** [Bugsnag] No API key configured, couldn't notify
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/cnchi.py", line 118, in do_activate
    window = main_window.MainWindow(self, cmd_line)
  File "/usr/share/cnchi/cnchi/main_window.py", line 211, in __init__
    self.pages["welcome"] = welcome.Welcome(self.params)
  File "/usr/share/cnchi/cnchi/welcome.py", line 81, in __init__
    image['height'])
GLib.Error: gdk-pixbuf-error-quark: Couldn't recognize the image file format for file '/usr/share/cnchi/data/images/welcome/try-it.svg' (3)
```

**cnchi log**

```
2016-05-23 03:48:29 [INFO] cnchi.py(225) setup_logging(): Sending Cnchi log messages to bugsnag server (using python-bugsnag).
2016-05-23 03:48:29 [INFO] cnchi.py(283) check_gtk_version(): Using GTK v3.20.5
2016-05-23 03:48:29 [INFO] cnchi.py(295) check_pyalpm_version(): Using pyalpm v0.8 as interface to libalpm v10.0.1
2016-05-23 03:48:29 [DEBUG] cnchi.py(322) check_iso_version(): Running from ISO version 16.5
\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\002016-05-23 03:48:29 [INFO] main_window.py(82) __init__(): Cnchi installer version 0.14.72
2016-05-23 03:48:29 [DEBUG] main_window.py(110) __init__(): Cnchi will use '/var/cache/pacman/pkg' as a source for cached xz packages
2016-05-23 03:48:29 [DEBUG] gtkbasebox.py(60) __init__(): Loading 'welcome' screen


### Additional Notes:

**Comment by karasu** [comment]
@LiberteCzech can you check your iso md5 sum? 

It looks like /usr/share/cnchi/data/images/welcome/try-it.svg is corrupted.

**Comment by LiberteCzech** [comment]
I will try to download and write to a USB flash again in the afternoon and try again.
But I'm pulling through software control against a single error writing to USB drive.

**Comment by karasu** [comment]
@LiberteCzech you can try to open that file, just to see if it's ok or not.

**Comment by LiberteCzech** [comment]
Image I can normally open manually but it is still error.

**MD5:** 89A67E5B930E8B6B89573A17612922D7

more precise
**SHA3_512:** EF2FA4A8B6C1F62E82025728C2CE8E94B5AF79A41926C286E346701B00D5052A4AD08ACA8C34FAA5C1D4CD48D3430740BB43492D51EF683C2970B200F6D8D320

**Comment by lots0logs** [comment]
@karasu I havent had a chance to test the new images yet. I will check them tonight.

**Comment by lots0logs** [comment]
Okay so it turns out that the problem was due to the gdk icon cache not being generated. Running the following command and then restarting Gnome Shell will resolve the issue:
```
sudo gdk-pixbuf-query-loaders --update-cache
```
To restart Gnome Shell: <kbd>Ctrl</kbd>+<kbd>R</kbd>+<kbd>Enter</kbd>

@karasu I think we should run this in postinstall just to be safe. I will try to remember to do it :sweat_smile:

**Comment by LiberteCzech** [comment]
When using `sudo gdk-pixbuf-query-loaders --update-cache` before installing. Cnchi starts.

**Comment by Mikaela** [comment]
@karasu @lots0logs Offtopic, but why are you so difficult to reach at Telegram? Is it something that we could do something to?

It should be just simple matter of pinning the tab web.telegram.org (if you don't want to install Telegram Desktop / Android/whatever) and possibly disabling the continuous beeping by clicking the group name and unchecking Notifications (so only @ mentions and replies cause notification).

Last night at 23:27+0300 (when I was sleeping), `<Wyn> @karasu0 @lotsoflogs , when you get a chance look into the github issues with the latest iso, we're slowly getting ran over for support` and the channel/group is full of these issues and linking to here so the topic was also changed to reflect it.

> Topic for #antergos is "https://antergos.com/ | IRC Help Guide: https://bit.ly/1VX6uz3 | FAQs: https://bit.ly/1jI44CT | Forum: https://bit.ly/1VWu9dz | Antergos News: https://bit.ly/1Lekts6 | Arch News: https://bit.ly/1sWFfoE | Current ISOs: 2016.05.24 https://bit.ly/25f2bQM | Don't ask Arch channels for support with Antergos | WE ARE AWARE OF ISSUES WITH THE LATEST ISO. PLEASE BEAR WITH US."

> -- Topic set by NanoSector (~Yoshi2889@simplemachines/friend/NanoSector) on 2016-05-24 23:32:36+0300

**Comment by satriani-vai** [comment]
```
[antergos@ant-16 ~]$ sudo gdk-pixbuf-query-loaders --update-cache
# ALT+F2, r, return :o)
[antergos@ant-16 ~]$ cnchi
2016-05-25 12:32:10 [INFO] cnchi.py(283) check_gtk_version(): Using GTK v3.20.6
2016-05-25 12:32:10 [INFO] cnchi.py(295) check_pyalpm_version(): Using pyalpm v0.8 as interface to libalpm v10.0.1
2016-05-25 12:32:10 [DEBUG] cnchi.py(322) check_iso_version(): Running from ISO version 16.5

```

**Comment by LiberteCzech** [comment]
**satriani-vai** I think it should be a root
`sudo cnchi`

**Comment by f4wks** [comment]
Plz someone looka at this (maybe its a way bigger issue?)
https://bugs.archlinux.org/task/49430

**Comment by lots0logs** [comment]
@f4wks I'm not sure what's causing that issue. The issue here is resolved by running the commands I mentioned. So long as you have internet access the ISO image will automatically fix the problem as soon as you boot into the live environment.

**Comment by f4wks** [comment]
@lots0logs my live .iso is not booting (the gui).
Internet is working ping on TTY2 works. 

sudo gdk-pixbuf-query-loaders --update-cache

Didn't help for me.

**Comment by lots0logs** [comment]
@f4wks Could you check the system journal and let us know what errors you see there? 
```
sudo journalctl -b -0
```
Press <kbd>End</kbd> to skip to the bottom and then work your way up (any errors related to the GUI will be towards the end anyway)

**Comment by osgyan** [comment]
sudo gdk-pixbuf-query-loaders --update-cache
Works for me! Thanks. Cnchi now started fine. Cnchi Version 0.14.85
