### ISSUE TITLE
Can't install necessary packages. Cnchi can't continue.

### ISSUE THREAD

**Issue by devland** [Antergos/Cnchi#603]
### Problem:
Can't install necessary packages. Cnchi can't continue.

### Steps To Reproduce:
Run installer and wait until  the very end of the package loading sequence.

### Log Files
```
2016-05-29 00:32:56 [INFO] slides.py(242) manage_events_from_cb_queue(): Checking disk space...
2016-05-29 00:32:56 [INFO] slides.py(242) manage_events_from_cb_queue(): Downloading pamac-4.1.0-1-x86_64...
2016-05-29 00:32:56 [INFO] slides.py(242) manage_events_from_cb_queue(): Checking disk space...
2016-05-29 00:32:56 [INFO] slides.py(242) manage_events_from_cb_queue(): Downloading missing keys into the keyring...
2016-05-29 00:32:57 [INFO] slides.py(242) manage_events_from_cb_queue(): Loading packages...
2016-05-29 00:33:05 [ERROR] pac.py(155) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 34 (invalid or corrupted package), []
2016-05-29 00:33:05 [DEBUG] pac.py(157) finalize_transaction(): Releasing alpm transaction...
2016-05-29 00:33:05 [DEBUG] pac.py(159) finalize_transaction(): Alpm transaction done.
2016-05-29 00:33:05 [ERROR] process.py(129) run(): "Can't install necessary packages. Cnchi can't continue."
2016-05-29 00:33:05 [ERROR] process.py(133) run(): Traceback (most recent call last):
2016-05-29 00:33:06 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 108, in run
    self.install_screen.run_install(self.pkg.packages, self.down.metalinks)
2016-05-29 00:33:06 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/advanced.py", line 2387, in run_install
    self.installation.start()
2016-05-29 00:33:06 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/misc/extra.py", line 191, in helper
    return func(*args, **kwargs)
2016-05-29 00:33:06 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 294, in start
    self.install_packages()
2016-05-29 00:33:06 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 460, in install_packages
    raise InstallError(txt)
2016-05-29 00:33:06 [ERROR] process.py(133) run(): misc.extra.InstallError: "Can't install necessary packages. Cnchi can't continue."
2016-05-29 00:33:07 [INFO] connectionpool.py(207) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2016-05-29 00:33:07 [DEBUG] connectionpool.py(386) _make_request(): "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=141271&result=False HTTP/1.1" 301 None
2016-05-29 00:33:07 [DEBUG] connectionpool.py(386) _make_request(): "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=141271&result=False HTTP/1.1" 200 None
```
### Additional Notes:
The problem seems to have appeared after the last iso update (28.05.2016).

**Comment by karasu** [comment]
>transaction failed, pm_errno 34 (invalid or corrupted package)

It could be that:
- The ISO has a corrupted package
- The ISO was not downloaded correctly (did you check md5 sum?)
- The package was not downloaded correctly (bad connection, bad mirror, ...)

Let me check the ISO. Which DE did you try to install?

**Comment by LiberteCzech** [comment]
**karasu**
I also have this problem, I tried **antergos-2016.05.28-x86_64** and really does not download packages.
Cnchi collapses suddenly. It was not for a particular package. I tried to manually adjust various combinations of mirrors with very good access, but cnchi crashes (unresponsive) system continues to operate.

**Comment by devland** [comment]
@karasu I tried to install cinnamon each time and each time it failed right at the end after the "loading packages" bar reached 100%.

Thanks for looking into this. :)

**Comment by karasu** [comment]
Geez... I performed a Gnome installation without issues, I forgot you were using Cinnamon. I'll try it again with Cinnamon just in case...

**Comment by karasu** [comment]
Installing Cinnamon here without issues... Guys, can you try it again just once more? Maybe there was some old package in one (or several) mirrors you were using.

**Comment by LiberteCzech** [comment]
Performed another tests 2, total 4.
I am unable to install.
I tried xfce, gnome, cinnamon 2x.
Every other mirrors, at last even another country.
Every crashed with another package.
The only suspect I noticed a large mining my cpu systemd-journald and kworker over 50%.
Also, six months ago we went retrieving packages list before downloading 2-3 times faster than now.
The actual download of the packages is slow and pauses between them to freeze completely.

**Comment by LiberteCzech** [comment]
I did a test with a previous version of the installation media **antergos-2016.05.24-x86_64**.
Downloading rapid and stable over time.
In the end, however, something causes a crash.
Here is the end **cnchi.log**

`2016-05-29 20:03:33 [ERROR] pac.py(155) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 34 (neplatný nebo poškozený balíček), []
2016-05-29 20:03:33 [DEBUG] pac.py(157) finalize_transaction(): Releasing alpm transaction...
2016-05-29 20:03:33 [DEBUG] pac.py(159) finalize_transaction(): Alpm transaction done.
2016-05-29 20:03:33 [ERROR] process.py(129) run(): __exit__
2016-05-29 20:03:33 [ERROR] process.py(133) run(): Traceback (most recent call last):
2016-05-29 20:03:33 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 108, in run
    self.install_screen.run_install(self.pkg.packages, self.down.metalinks)
2016-05-29 20:03:33 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/advanced.py", line 2387, in run_install
    self.installation.start()
2016-05-29 20:03:33 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/misc/extra.py", line 191, in helper
    return func(*args, **kwargs)
2016-05-29 20:03:33 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 294, in start
    self.install_packages()
2016-05-29 20:03:33 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 449, in install_packages
    with misc.raised_privileges:
2016-05-29 20:03:33 [ERROR] process.py(133) run(): AttributeError: __exit__
2016-05-29 20:03:34 [INFO] connectionpool.py(213) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2016-05-29 20:03:34 [DEBUG] connectionpool.py(395) _make_request(): "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=142367&result=False HTTP/1.1" 301 None
2016-05-29 20:03:35 [DEBUG] connectionpool.py(395) _make_request(): "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=142367&result=False HTTP/1.1" 200 None
`

**Comment by devland** [comment]
I tried again just now with the same error at the end of the package loading phase.

`2016-05-30 05:55:13 [INFO] slides.py(242) manage_events_from_cb_queue(): Downloading cinnamon-session-3.0.1-1-x86_64...
2016-05-30 05:55:13 [INFO] slides.py(242) manage_events_from_cb_queue(): Checking disk space...
2016-05-30 05:55:13 [INFO] slides.py(242) manage_events_from_cb_queue(): Downloading missing keys into the keyring...
2016-05-30 05:55:15 [INFO] slides.py(242) manage_events_from_cb_queue(): Loading packages...
2016-05-30 05:55:24 [ERROR] pac.py(155) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 34 (invalid or corrupted package), []
2016-05-30 05:55:24 [DEBUG] pac.py(157) finalize_transaction(): Releasing alpm transaction...
2016-05-30 05:55:24 [DEBUG] pac.py(159) finalize_transaction(): Alpm transaction done.
2016-05-30 05:55:24 [ERROR] process.py(129) run(): "Can't install necessary packages. Cnchi can't continue."
2016-05-30 05:55:24 [ERROR] process.py(133) run(): Traceback (most recent call last):
2016-05-30 05:55:24 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 108, in run
    self.install_screen.run_install(self.pkg.packages, self.down.metalinks)
2016-05-30 05:55:24 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/advanced.py", line 2387, in run_install
    self.installation.start()
2016-05-30 05:55:25 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/misc/extra.py", line 191, in helper
    return func(*args, **kwargs)
2016-05-30 05:55:25 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 294, in start
    self.install_packages()
2016-05-30 05:55:25 [ERROR] process.py(133) run():   File "/usr/share/cnchi/cnchi/installation/install.py", line 460, in install_packages
    raise InstallError(txt)
2016-05-30 05:55:25 [ERROR] process.py(133) run(): misc.extra.InstallError: "Can't install necessary packages. Cnchi can't continue."
2016-05-30 05:55:25 [INFO] connectionpool.py(213) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2016-05-30 05:55:26 [DEBUG] connectionpool.py(395) _make_request(): "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=142850&result=False HTTP/1.1" 301 None
2016-05-30 05:55:26 [DEBUG] connectionpool.py(395) _make_request(): "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=142850&result=False HTTP/1.1" 200 None`

**Comment by bidlocode** [comment]
> I tried again just now with the same error at the end of the package loading phase.

I'm experiencing exactly the same behavior with **antergos-2016.05.28-x86_64** and with previous iso's too. About a week ago it was fine and working.

**Comment by kovacskri** [comment]
Can confirm that the installation doesn't work with cinnamon. Worked fine when I chose Gnome and no extra packages though.

**Comment by devland** [comment]
The issues appears to have been fixed as detailed in #605.
Thanks for all the help. :)

**Comment by awnumar** [comment]
Ah, I didn't see this issue was here already. I'm experiencing this exact now, and opened a new issue at #799. Any help?

**Comment by etaggus** [comment]
I'm having this issue when installing the latest version of Antergos with KDE.

I get errors installing the desktop-settings package as below:

```
2018-10-29 23:48:09 [DEBUG  ] https://antergos.mirror.constant.com:443 "GET /antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-29 23:48:10 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-29 23:48:10 [DEBUG  ] Can't download https://antergos.mirror.constant.com/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-29 23:48:30 [DEBUG  ] Starting new HTTPS connection (1): mirror.alpix.eu:443  (connectionpool.py:823)
2018-10-29 23:48:31 [DEBUG  ] https://mirror.alpix.eu:443 "GET /antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-29 23:48:36 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-29 23:48:36 [DEBUG  ] Can't download https://mirror.alpix.eu/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-29 23:48:56 [DEBUG  ] Starting new HTTPS connection (1): mirror.nl.leaseweb.net:443  (connectionpool.py:823)
2018-10-29 23:48:57 [DEBUG  ] https://mirror.nl.leaseweb.net:443 "GET /antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-29 23:48:59 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-29 23:48:59 [DEBUG  ] Can't download https://mirror.nl.leaseweb.net/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-29 23:49:19 [DEBUG  ] Starting new HTTPS connection (1): glua.ua.pt:443  (connectionpool.py:823)
2018-10-29 23:49:27 [DEBUG  ] https://glua.ua.pt:443 "GET /pub/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-29 23:49:29 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-29 23:49:29 [DEBUG  ] Can't download https://glua.ua.pt/pub/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-29 23:49:49 [DEBUG  ] Starting new HTTPS connection (1): mirrors.nic.cz:443  (connectionpool.py:823)
2018-10-29 23:49:51 [DEBUG  ] https://mirrors.nic.cz:443 "GET /antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-29 23:49:53 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-29 23:49:53 [DEBUG  ] Can't download https://mirrors.nic.cz/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-29 23:50:13 [DEBUG  ] Starting new HTTPS connection (1): ftp.acc.umu.se:443  (connectionpool.py:823)
2018-10-29 23:50:14 [DEBUG  ] https://ftp.acc.umu.se:443 "GET /mirror/antergos.com/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-29 23:50:16 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-29 23:50:16 [DEBUG  ] Can't download https://ftp.acc.umu.se/mirror/antergos.com/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-29 23:50:36 [DEBUG  ] Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443  (connectionpool.py:823)
2018-10-29 23:50:38 [DEBUG  ] https://mirrors.tuna.tsinghua.edu.cn:443 "GET /antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz HTTP/1.1" 200 1183332  (connectionpool.py:393)
2018-10-29 23:50:40 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-29 23:50:40 [DEBUG  ] Can't download https://mirrors.tuna.tsinghua.edu.cn/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-29 23:51:00 [ERROR  ] Can't download antergos-desktop-settings-1.14-1-any.pkg.tar.xz, even after trying all available mirrors  (download_requests.py:185)
2018-10-29 23:51:00 [ERROR  ] "Can't download needed packages. Cnchi can't continue."  (process.py:186)
2018-10-29 23:51:00 [ERROR  ] Traceback (most recent call last):  (process.py:191)
2018-10-29 23:51:00 [ERROR  ]   File "/usr/share/cnchi/src/installation/process.py", line 168, in run
    self.pkg.packages, self.down.metalinks)  (process.py:191)
2018-10-29 23:51:00 [ERROR  ]   File "/usr/share/cnchi/src/pages/automatic.py", line 281, in run_install
    self.installation.run()  (process.py:191)
2018-10-29 23:51:00 [ERROR  ]   File "/usr/share/cnchi/src/misc/extra.py", line 194, in helper
    return func(*args, **kwargs)  (process.py:191)
2018-10-29 23:51:00 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 296, in run
    self.download_packages()  (process.py:191)
2018-10-29 23:51:00 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 356, in download_packages
    download_packages.start_download(self.metalinks)  (process.py:191)
2018-10-29 23:51:00 [ERROR  ]   File "/usr/share/cnchi/src/download/download.py", line 114, in start_download
    raise misc.InstallError(txt)  (process.py:191)
2018-10-29 23:51:00 [ERROR  ] misc.extra.InstallError: "Can't download needed packages. Cnchi can't continue."  (process.py:191)
2018-10-29 23:51:00 [DEBUG  ] Starting new HTTP connection (1): build.antergos.com:80  (connectionpool.py:205)
2018-10-29 23:51:01 [DEBUG  ] http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 301 None  (connectionpool.py:393)
2018-10-29 23:51:01 [DEBUG  ] http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 200 None  (connectionpool.py:393)
```

I've tried with a fresh ISO, and tried following the steps in #799 to no avail. I'm installing no extra packages, just KDE with LUKS encryption. I'll try an install with a different DE and report back.

**Comment by etaggus** [comment]
Apologies. Appears to be related to #1108 , I'll try with the latest installer.
