### ISSUE TITLE
Cnchi CSS (I think) error.

### ISSUE THREAD

**Issue by pixiesky** [Antergos/Cnchi#607]
### Problem:
After Cnchi updates it's unable to properly restart and presents the following error (in command line):

**GLib.Error: gtk-css-provider-error-quark: <data>:54:14'min-height' is not a valid property name (3)**

`2016-06-01 21:26:54 [INFO] cnchi.py(283) check_gtk_version(): Using GTK v3.18.9
2016-06-01 21:26:54 [INFO] cnchi.py(295) check_pyalpm_version(): Using pyalpm v0.8 as interface to libalpm v10.0.1
2016-06-01 21:26:54 [DEBUG] cnchi.py(322) check_iso_version(): Running from ISO version 16.3
2016-06-01 21:26:58 [INFO] main_window.py(82) __init__(): Cnchi installer version 0.14.89
2016-06-01 21:26:58 [DEBUG] main_window.py(110) __init__(): Cnchi will use '/var/cache/pacman/pkg' as a source for cached xz packages
2016-06-01 21:26:58 [DEBUG] gtkbasebox.py(60) __init__(): Loading 'welcome' screen
2016-06-01 21:26:58 [INFO] main_window.py(299) header_for_all_callback(): fired!
** [Bugsnag] No API key configured, couldn't notify
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/cnchi.py", line 118, in do_activate
    window = main_window.MainWindow(self, cmd_line)
  File "/usr/share/cnchi/cnchi/main_window.py", line 266, in __init__
    style_provider.load_from_data(css_data)
GLib.Error: gtk-css-provider-error-quark: <data>:54:14'min-height' is not a valid property name (3)
`

### Steps To Reproduce:
To reproduce, boot up the live "CD" and connect to the internet and wait until the update completes. 

### Additional Notes:
(I was always a few steps into the install.)

**Comment by Archernoob** [comment]
Which version of iso you use and how you update cnchi?

**Comment by pixiesky** [comment]
@Archernoob I wouldn't know how to get the ISO version but the device name is _ant-16.3_ so I assume that is the answer. Feels right some how.

**Comment by lots0logs** [comment]
Please ensure you are using the latest ISO. It looks like you are using an ISO that has GTK 3.18 which doesnt support the new CSS properties in 3.20

**Comment by pixiesky** [comment]
Ahhh! Okay thanks. Never occurred to me.
