### ISSUE TITLE
Cnchi won't start

### ISSUE THREAD

**Issue by NickGeek** [Antergos/Cnchi#613]
```
[antergos@ant-15 ~]$ sudo cnchi
2016-06-10 19:19:51 [INFO] cnchi.py(283) check_gtk_version(): Using GTK v3.18.6
2016-06-10 19:19:51 [INFO] cnchi.py(295) check_pyalpm_version(): Using pyalpm v0.7 as interface to libalpm v9.0.1
2016-06-10 19:19:51 [DEBUG] cnchi.py(322) check_iso_version(): Running from ISO version 15.12
2016-06-10 19:19:54 [INFO] main_window.py(82) __init__(): Cnchi installer version 0.14.94
2016-06-10 19:19:54 [DEBUG] main_window.py(110) __init__(): Cnchi will use '/var/cache/pacman/pkg' as a source for cached xz packages
2016-06-10 19:19:54 [DEBUG] gtkbasebox.py(60) __init__(): Loading 'welcome' screen
2016-06-10 19:19:54 [INFO] main_window.py(299) header_for_all_callback(): fired!
** [Bugsnag] No API key configured, couldn't notify
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/cnchi.py", line 118, in do_activate
    window = main_window.MainWindow(self, cmd_line)
  File "/usr/share/cnchi/cnchi/main_window.py", line 266, in __init__
    style_provider.load_from_data(css_data)
GLib.Error: gtk-css-provider-error-quark: <data>:54:14'min-height' is not a valid property name (3)
```

**Comment by lots0logs** [comment]
Hi. You are using an old ISO that doesnt have GTK 3.20 on it. You will need to download the latest ISO I'm afraid. Sorry about that!
