### ISSUE TITLE
Cannot start cnchi

### ISSUE THREAD

**Issue by ATrigger** [Antergos/Cnchi#624]
### Problem:
Couldn't start Cnchi

### Steps To Reproduce:
1. Boot from antergos livecd.
2. Launch Cnchi
3. It will update itself and close itself.
4. You can't start cnchi after that

### Log Files
[antergos@ant-16 ~]$ sudo cnchi
2016-06-21 22:13:33 [INFO] cnchi.py(283) check_gtk_version(): Using GTK v3.18.9
2016-06-21 22:13:33 [INFO] cnchi.py(295) check_pyalpm_version(): Using pyalpm v0.8 as interface to libalpm v10.0.1
2016-06-21 22:13:33 [DEBUG] cnchi.py(322) check_iso_version(): Running from ISO version 16.3
2016-06-21 22:13:36 [INFO] main_window.py(82) __init__(): Cnchi installer version 0.14.106
2016-06-21 22:13:36 [DEBUG] main_window.py(110) __init__(): Cnchi will use '/var/cache/pacman/pkg' as a source for cached xz packages
2016-06-21 22:13:36 [DEBUG] gtkbasebox.py(60) __init__(): Loading 'welcome' screen
2016-06-21 22:13:36 [INFO] main_window.py(299) header_for_all_callback(): fired!
** [Bugsnag] No API key configured, couldn't notify
Traceback (most recent call last):
  File "/usr/share/cnchi/cnchi/cnchi.py", line 118, in do_activate
    window = main_window.MainWindow(self, cmd_line)
  File "/usr/share/cnchi/cnchi/main_window.py", line 266, in __init__
    style_provider.load_from_data(css_data)
GLib.Error: gtk-css-provider-error-quark: <data>:54:14'min-height' is not a valid property name (3)

**Comment by ATrigger** [comment]
Workaround:
cd /var/cache/pacman/pkg
and downgrade cnchi to version that was present on livecd ( 0.14.68-1 in my case)

**Comment by lots0logs** [comment]
Cnchi will launch itself automatically. You should not launch it manually. Please try to boot the livecd, connect your your internet connections, and allow the updater to do its thing (after which cnchi will open automatically)

**Comment by Wyn10** [comment]
@lots0logs Close...?
