### ISSUE TITLE
Error creating metalink for package zd1211-firmware (iso 16.9, cnchi 0.14.187)

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#663]
### Problem:
Can't create metalink for package zd1211-firmware, so installation stops.

### Steps To Reproduce:
1. Try to install Antergos Plasma KDE

### Log
```
2016-10-21 09:14:34 [DEBUG] cnchi.py(322) check_iso_version(): Running from ISO version 16.9
2016-10-21 09:14:34 [INFO] main_window.py(82) __init__(): Cnchi installer version 0.14.187
```
and

```
2016-10-21 09:19:19 [DEBUG] select_packages.py(110) create_package_list(): Packages selected
2016-10-21 09:19:19 [DEBUG] pac.py(119) initialize_alpm(): ALPM initialised with root dir / and db path /var/lib/pacman
2016-10-21 09:19:19 [DEBUG] pac.py(96) __init__(): ALPM REPO DB ORDER IS: ['antergos', 'core', 'extra', 'community', 'multilib']
2016-10-21 09:19:19 [ERROR] metalink.py(117) create(): Unable to create download queue for package zd1211-firmware. An exception of type TypeError occured. Arguments:
("'NoneType' object is not subscriptable",)
2016-10-21 09:19:19 [ERROR] download.py(145) create_metalinks_list(): Error creating metalink for package zd1211-firmware. Installation will stop
2016-10-21 09:19:19 [ERROR] download.py(177) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
("Error en crear el metaenllaç per al paquet zd1211-firmware. La instal·lació s'aturarà.",)
2016-10-21 09:19:19 [ERROR] process.py(128) run(): 'No es pot crear la llista de descàrrega de paquets (metaenllaços).'
2016-10-21 09:19:19 [ERROR] process.py(132) run(): Traceback (most recent call last):
2016-10-21 09:19:19 [ERROR] process.py(132) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 93, in run
    self.create_metalinks_list()
2016-10-21 09:19:19 [ERROR] process.py(132) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 83, in create_metalinks_list
    raise misc.InstallError(txt)
2016-10-21 09:19:19 [ERROR] process.py(132) run(): misc.extra.InstallError: 'No es pot crear la llista de descàrrega de paquets (metaenllaços).'
```

**Comment by nebkat** [comment]
Was this ever resolved? I'm getting the same issue with latest ISO.
