### ISSUE TITLE
can't install necessary packages. error 127041

### ISSUE THREAD

**Issue by HarshilPatel007** [Antergos/Cnchi#811]
### Problem:
Error While Installing In Final Step.

### Steps To Reproduce:
1. DE : XFCE
2. ISO : latest antergos os
3.

### Log Files
2017-11-03 20:47:12 [INFO] slides.py(276) manage_events_from_cb_queue(): Checking file conflicts...
2017-11-03 20:47:14 [ERROR] pac.py(164) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 49 (conflicting files), [('bash', '/install/etc/skel/.bashrc', 'antergos-desktop-settings')]
2017-11-03 20:47:14 [DEBUG] pac.py(167) finalize_transaction(): Releasing alpm transaction...
2017-11-03 20:47:14 [DEBUG] pac.py(169) finalize_transaction(): Alpm transaction done.
2017-11-03 20:47:14 [ERROR] process.py(130) run(): "Can't install necessary packages. Cnchi can't continue."
2017-11-03 20:47:14 [ERROR] process.py(135) run(): Traceback (most recent call last):
2017-11-03 20:47:14 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 108, in run
    self.pkg.packages, self.down.metalinks)
2017-11-03 20:47:14 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/pages/automatic.py", line 367, in run_install
    self.installation.start()
2017-11-03 20:47:14 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/misc/extra.py", line 192, in helper
    return func(*args, **kwargs)
2017-11-03 20:47:14 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/install.py", line 318, in start
    self.install_packages()
2017-11-03 20:47:14 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/install.py", line 529, in install_packages
    raise InstallError(txt)
2017-11-03 20:47:14 [ERROR] process.py(135) run(): misc.extra.InstallError: "Can't install necessary packages. Cnchi can't continue."
2017-11-03 20:47:14 [DEBUG] connectionpool.py(208) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2017-11-03 20:47:15 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=127041&result=False HTTP/1.1" 301 None
2017-11-03 20:47:15 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=127041&result=False HTTP/1.1" 200 None

**Comment by karasu** [comment]
https://github.com/Antergos/Cnchi/issues/809
