### ISSUE TITLE
Errors 137619 & 138097

### ISSUE THREAD

**Issue by HawktheSlayer** [Antergos/Cnchi#814]
### Problem:
*Replace this line with a brief summary of the problem.*

### Steps To Reproduce:
1.Installation process using 17.11 iso
2.All goes well until you try and input user details
3. 

### Log Files
- Use a service like http://paste2.org/ to provide links to the logs.
- Link to /tmp/cnchi.log output.
- Link to /tmp/postinstall.log.

**Comment by karasu** [comment]
Could it be that it was installing Deepin DE?

You didn't provide any logs...

**Comment by LinuxUserGD** [comment]
I can't currently install deepin with Cnchi:
```
2018-05-23 15:50:47 [ERROR] metalink.py(132) create(): Can't resolve these dependencies: deepin-wm-switcher 
2018-05-23 15:50:47 [ERROR] download.py(150) create_metalinks_list(): Error creating metalink for package antergos-deepin-meta. Installation will stop
2018-05-23 15:50:47 [ERROR] download.py(182) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package antergos-deepin-meta. Installation will stop',)
2018-05-23 15:50:47 [ERROR] process.py(130) run(): 'Cannot create download package list (metalinks).'
2018-05-23 15:50:47 [ERROR] process.py(135) run(): Traceback (most recent call last):
2018-05-23 15:50:47 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 92, in run
    self.create_metalinks_list()
2018-05-23 15:50:47 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 82, in create_metalinks_list
    raise misc.InstallError(txt)
2018-05-23 15:50:47 [ERROR] process.py(135) run(): misc.extra.InstallError: 'Cannot create download package list (metalinks).'
[antergos@ant-18.5 ~]$ 
```
Maybe the missing package ```deepin-vm-switcher``` should be ```startdde```?

**Comment by karasu** [comment]
This has been addressed. Please @LinuxUserGD , could you please tell us if it is working for you?

**Comment by LinuxUserGD** [comment]
I get the same error using cnchi 0.14.426

**Comment by dbqeo** [comment]
I got the same error using cnchi 0.16.4:

```
2018-05-27 21:08:14 [ERROR] metalink.py(133) create(): Can't resolve these dependencies: deepin-wm-switcher 
2018-05-27 21:08:14 [ERROR] download.py(157) create_metalinks_list(): Error creating metalink for package antergos-deepin-meta. Installation will stop
2018-05-27 21:08:14 [ERROR] download.py(189) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package antergos-deepin-meta. Installation will stop',)
2018-05-27 21:08:14 [ERROR] process.py(137) run(): 'Cannot create download package list (metalinks).'
2018-05-27 21:08:14 [ERROR] process.py(142) run(): Traceback (most recent call last):
2018-05-27 21:08:14 [ERROR] process.py(142) run():   File "/usr/share/cnchi/src/installation/process.py", line 99, in run
    self.create_metalinks_list()
2018-05-27 21:08:14 [ERROR] process.py(142) run():   File "/usr/share/cnchi/src/installation/process.py", line 89, in create_metalinks_list
    raise misc.InstallError(txt)
2018-05-27 21:08:14 [ERROR] process.py(142) run(): misc.extra.InstallError: 'Cannot create download package list (metalinks).'
```

I resolved the error by replacing the broken/nonexistent package `antergos-deepin-meta` with `startdde` in `/usr/share/cnchi/data/packages.xml`.

**Comment by karasu** [comment]
`antergos-deepin-meta` is being rebuilt.

It will take a few hours to be replicated in all mirrors.

Sorry for the inconvenience.

**Comment by LinuxUserGD** [comment]
Thank you, it works now :+1:
