### ISSUE TITLE
Cnchi 

### ISSUE THREAD

**Issue by Akinevz** [Antergos/Cnchi#865]
# Problem:
Cnchi stops with error xxxxxx after getting to the user set up stage.

# Steps To Reproduce:
boot live installer and wait for cnchi to update
after successful update, choose anything
from about near instantly to a few seconds after, installer halts with a numerical error

# Logs:
Not attaching since they vary and do not include the ACTUAL relevant information

# Resolution:
* After booting liveiso, close cnchi
* Navigate to the .db folder (`cd /var/lib/pacman/sync`)
* Analyse corrupted databases (`file *`)
  * Notably, antergos.db comes up as an HTML document (long lines) instead of gzip compressed data
* Remove corrupted database files (`sudo rm anter*`)
* Remove **THE DEAD MIRROR** from `/etc/pacman.d/antergos-mirrorlist`
  * Notably, `mirror.finn.lu`
  * To be safe I enabled the Czech mirror (I'm in UK)
  * Can the maintainers of antergos please sort the mirrors by geolocation rather than bundling them all under US?
* Run `pacman -Syy` to redownload packagelists
  * If pacman doesn't complain you're in the clear
* Proceed with your installation as required
  * To be safe I switch to "manual" mirror selection mode and leave them as is

**Comment by Akinevz** [comment]
Interesting. Perhaps the same error message is generated for different errors?

@hippietilley may I see the output of `sudo pacman -Syy`?

**Comment by khbecker** [comment]
I'm having the same problem. It appears to be the same [issue discussed on the Antergos forum](https://forum.antergos.com/topic/9721/can-t-install-error-1076268/2?page=1). Apparently Arch moving gksu to the AUR has caused problems.

**Comment by hippietilley** [comment]
@Akinevz Here is my <code>sudo pacman -Syy</code> output:
<code>
<pre>
[antergos@ant-18.4 ~]$ sudo pacman -Syy
error: could not register &apos;multilib&apos; database (database already registered)
:: Synchronizing package databases...
 antergos                 157.0 KiB  1481K/s 00:00 [######################] 100%
 core                     129.7 KiB   598K/s 00:00 [######################] 100%
 extra                   1596.1 KiB  7.99M/s 00:00 [######################] 100%
 community                  4.3 MiB  24.1M/s 00:00 [######################] 100%
 multilib                 171.1 KiB  41.8M/s 00:00 [######################] 100%</pre>
</code>

**Comment by Akinevz** [comment]
Ah completely forgot! Will add this in a second to OP, but there is a **duplicate** multilib in the pacman.conf. I wasn't sure if it was an error or not, but I had removed it anyway. Check if `/etc/pacman.conf` contains two declarations for multilib. I left in the second one that had an uncommented `SigLevel`.

**Comment by Akinevz** [comment]
@khbecker I doubt the gksu removal caused this, since I recall having this issue even back in some 2017 release. In my `cnchi.log` there were only errors related to packages, nothing about permissions.

**Comment by khbecker** [comment]
I removed the extra multilib in pacman.conf and now have the following normal output for pacman -Syy, but still have the problem. I've checked all the mirrors in my mirrorlists and I can access all of them. Any other ideas?

> :: Synchronizing package databases...
>  antergos                 157.0 KiB  1804K/s 00:00 [######################] 100%
> core                     129.7 KiB  1996K/s 00:00 [######################] 100%
> extra                   1596.1 KiB  9.28M/s 00:00 [######################] 100%
>  community                  4.3 MiB  11.1M/s 00:00 [######################] 100%
> multilib                 171.1 KiB  11.1M/s 00:00 [######################] 100%

**Comment by hippietilley** [comment]
I removed the duplicate <code>multilib</code>. Installation still failed, though the error number changed. They seem to change arbitrarily....  

It always fails at this point:
<code>
<pre>2018-04-26 19:42:22 [DEBUG] connectionpool.py(208) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2018-04-26 19:42:22 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 &quot;GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&amp;install_id=1082783&amp;result=False HTTP/1.1&quot; 301 None
2018-04-26 19:42:22 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 &quot;GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&amp;install_id=1082783&amp;result=False HTTP/1.1&quot; 200 None
</pre>
</code>

**Comment by Akinevz** [comment]
@hippietilley @khbecker could you both attach the latest cnchi.logs so I can give them a quick scan through to see if the error that tripped me up is the same?

**Comment by hippietilley** [comment]
Here you go! [cnchi.log](https://github.com/Antergos/Cnchi/files/1952769/cnchi.log)

**Comment by khbecker** [comment]
Here's mine: 
[cnchi.log](https://github.com/Antergos/Cnchi/files/1952790/cnchi.log)

**Comment by hippietilley** [comment]
They seem to be failing on different packages...

**Comment by Akinevz** [comment]
hmm, in both logs the first instance of an error appears as 
```
2018-04-26 19:46:43 [ERROR] select_packages.py(291) select_packages(): Error in hardware module. An exception of type FileNotFoundError occured. Arguments:
(2, 'No such file or directory')
```
which I don't recall having, but then I might have just skipped it. I'll have free time tomorrow to boot up another liveISO and see if I get exactly the same message.

The installer then trips up on downloading `pkgfile` and `antergos-midnight-timers` for @hippietilley and @khbecker respectively, in the same way mine did. I wonder if there is a way to enable more verbose messages for metalink.py?

In the mean time I'd recommend to maybe re-check all of the other steps, just to eliminate the possibility of a problem coming from another step.

**Comment by hippietilley** [comment]
I ran it again. This time is tripped up on <code>python-pyqt5</code>.

**Comment by Akinevz** [comment]
Hmm, odd. The dbs in `/var/lib/pacman/sync` are definitelly all gzips, right?

**Comment by hippietilley** [comment]
I tried messing around with this <a href="https://github.com/Antergos/Cnchi/issues/845#issuecomment-374779410">solution</a>. But it just fails on a different package each time.

**Comment by khbecker** [comment]
@hippietilley I tried that solution too. Same results here.

**Comment by dessalines** [comment]
This is getting ridiculous, just tried a ton of these different methods to fix this error, and none of them worked.

**Comment by Akinevz** [comment]
@Deedasmi could you also drop me your log file so I've got another reference?

I'm beginning to believe there might be another category of issue with the same error.  
Doesn't help that the error code is random every time :expressionless:

**Comment by dessalines** [comment]
@Akinevz 
```
2018-04-26 23:45:31 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package chromium for feature chromium
2018-04-26 23:45:31 [DEBUG] select_packages.py(344) select_packages(): All features needed packages have been added
2018-04-26 23:45:31 [DEBUG] select_packages.py(361) select_packages(): Packages list: grub,antergos-gnome-meta,sudo,e2fsprogs,unrar,base-devel,net-tools,antergos-midnight-timers,btrfs-progs,efibootmgr,whois,alsa-utils,dmraid,tar,os-prober,python2-gnomekeyring,wireless_tools,ntfs-3g,python-pyqt5,acpid,exfat-utils,splix,screenfetch,htop,b43-fwcutter,gsfonts,nilfs-utils,mlocate,dosfstools,terminus-font,crda,base,cifs-utils,modemmanager,chromium,usb_modeswitch,bash-completion,bind-tools,ipw2100-fw,pkgfile,antergos-common-meta,hplip,f2fs-tools,wpa_actiond,unzip,nfs-utils,antergos-keyring,openssh,antergos-mirrorlist,grub2-theme-antergos,cups-pk-helper,reiserfsprogs,cups,wget,intel-ucode,reflector,xfsprogs,haveged,networkmanager,python-gobject,gzip,zd1211-firmware,ipw2200-fw,jfsutils,system-config-printer,antergos-desktop-settings
2018-04-26 23:45:31 [DEBUG] select_packages.py(111) create_package_list(): Packages selected
2018-04-26 23:45:31 [DEBUG] pac.py(122) initialize_alpm(): ALPM initialised with root dir / and db path /var/lib/pacman
2018-04-26 23:45:31 [DEBUG] pac.py(98) __init__(): ALPM repository database order is: ['antergos', 'core', 'extra', 'community', 'multilib']
2018-04-26 23:45:31 [ERROR] metalink.py(118) create(): Unable to create download queue for package grub. An exception of type TypeError occured. Arguments:
("'NoneType' object is not subscriptable",)
2018-04-26 23:45:31 [ERROR] download.py(150) create_metalinks_list(): Error creating metalink for package grub. Installation will stop
2018-04-26 23:45:31 [ERROR] download.py(182) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package grub. Installation will stop',)
2018-04-26 23:45:31 [ERROR] process.py(130) run(): 'Cannot create download package list (metalinks).'
2018-04-26 23:45:31 [ERROR] process.py(135) run(): Traceback (most recent call last):
2018-04-26 23:45:31 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 92, in run
    self.create_metalinks_list()
2018-04-26 23:45:31 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 82, in create_metalinks_list
    raise misc.InstallError(txt)
2018-04-26 23:45:31 [ERROR] process.py(135) run(): misc.extra.InstallError: 'Cannot create download package list (metalinks).'
2018-04-26 23:45:32 [INFO] slides.py(276) manage_events_from_cb_queue(): Creating the list of packages to download...
2018-04-26 23:45:32 [DEBUG] connectionpool.py(208) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2018-04-26 23:45:33 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=1083458&result=False HTTP/1.1" 301 None
2018-04-26 23:45:33 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=1083458&result=False HTTP/1.1" 200 None

(gst-plugin-scanner:2539): GStreamer-WARNING **: 23:45:35.572: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstfluidsynthmidi.so': libfluidsynth.so.1: cannot open shared object file: No such file or directory

(gst-plugin-scanner:2539): GStreamer-WARNING **: 23:45:35.608: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstkate.so': libkate.so.1: cannot open shared object file: No such file or directory

(gst-plugin-scanner:2539): GStreamer-WARNING **: 23:45:35.664: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstlv2.so': liblilv-0.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:2539): GStreamer-WARNING **: 23:45:35.680: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstopencv.so': libopencv_bgsegm.so.3.4: cannot open shared object file: No such file or directory

(gst-plugin-scanner:2539): GStreamer-WARNING **: 23:45:35.704: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstqmlgl.so': libQt5Quick.so.5: cannot open shared object file: No such file or directory
error: XDG_RUNTIME_DIR not set in the environment.

(gst-plugin-scanner:2539): GStreamer-WARNING **: 23:45:36.281: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstzbar.so': libzbar.so.0: cannot open shared object file: No such file or directory
1   0x7fd11311bdc8 /usr/lib/libjavascriptcoregtk-4.0.so.18(WTFCrash+0x18) [0x7fd11311bdc8]
2   0x7fd11728f7eb /usr/lib/libwebkit2gtk-4.0.so.37(+0x7817eb) [0x7fd11728f7eb]
3   0x7fd1172ca8c1 /usr/lib/libwebkit2gtk-4.0.so.37(+0x7bc8c1) [0x7fd1172ca8c1]
4   0x7fd1172cad58 /usr/lib/libwebkit2gtk-4.0.so.37(+0x7bcd58) [0x7fd1172cad58]
5   0x7fd1172cb411 /usr/lib/libwebkit2gtk-4.0.so.37(+0x7bd411) [0x7fd1172cb411]
6   0x7fd11818d90a /usr/lib/libwebkit2gtk-4.0.so.37(+0x167f90a) [0x7fd11818d90a]
7   0x7fd11818e236 /usr/lib/libwebkit2gtk-4.0.so.37(+0x1680236) [0x7fd11818e236]
8   0x7fd118181c85 /usr/lib/libwebkit2gtk-4.0.so.37(+0x1673c85) [0x7fd118181c85]
9   0x7fd11818a100 /usr/lib/libwebkit2gtk-4.0.so.37(+0x167c100) [0x7fd11818a100]
10  0x7fd118186b10 /usr/lib/libwebkit2gtk-4.0.so.37(+0x1678b10) [0x7fd118186b10]
11  0x7fd118193478 /usr/lib/libwebkit2gtk-4.0.so.37(+0x1685478) [0x7fd118193478]
12  0x7fd1181940fe /usr/lib/libwebkit2gtk-4.0.so.37(+0x16860fe) [0x7fd1181940fe]
13  0x7fd118181692 /usr/lib/libwebkit2gtk-4.0.so.37(+0x1673692) [0x7fd118181692]
14  0x7fd11819313b /usr/lib/libwebkit2gtk-4.0.so.37(+0x168513b) [0x7fd11819313b]
15  0x7fd118193241 /usr/lib/libwebkit2gtk-4.0.so.37(+0x1685241) [0x7fd118193241]
16  0x7fd1172c67c1 /usr/lib/libwebkit2gtk-4.0.so.37(+0x7b87c1) [0x7fd1172c67c1]
17  0x7fd1181c9674 /usr/lib/libwebkit2gtk-4.0.so.37(+0x16bb674) [0x7fd1181c9674]
18  0x7fd1181ce151 /usr/lib/libwebkit2gtk-4.0.so.37(+0x16c0151) [0x7fd1181ce151]
19  0x7fd1181cee29 /usr/lib/libwebkit2gtk-4.0.so.37(+0x16c0e29) [0x7fd1181cee29]
20  0x7fd117fd63ae /usr/lib/libwebkit2gtk-4.0.so.37(+0x14c83ae) [0x7fd117fd63ae]
21  0x7fd117fd6a49 /usr/lib/libwebkit2gtk-4.0.so.37(+0x14c8a49) [0x7fd117fd6a49]
22  0x7fd117e4c11e /usr/lib/libwebkit2gtk-4.0.so.37(+0x133e11e) [0x7fd117e4c11e]
23  0x7fd117e48f3f /usr/lib/libwebkit2gtk-4.0.so.37(+0x133af3f) [0x7fd117e48f3f]
24  0x7fd117e4f084 /usr/lib/libwebkit2gtk-4.0.so.37(+0x1341084) [0x7fd117e4f084]
25  0x7fd117737016 /usr/lib/libwebkit2gtk-4.0.so.37(+0xc29016) [0x7fd117737016]
26  0x7fd112e471ee /usr/lib/libjavascriptcoregtk-4.0.so.18(_ZN3JSC16callCustomSetterEPNS_9ExecStateEPFbS1_llEbNS_7JSValueES4_+0xe) [0x7fd112e471ee]
27  0x7fd112eeefbf /usr/lib/libjavascriptcoregtk-4.0.so.18(_ZN3JSC8JSObject13putInlineSlowEPNS_9ExecStateENS_12PropertyNameENS_7JSValueERNS_15PutPropertySlotE+0x2bf) [0x7fd112eeefbf]
28  0x7fd112ccde68 /usr/lib/libjavascriptcoregtk-4.0.so.18(+0x9efe68) [0x7fd112ccde68]
29  0x7fd112cb9992 /usr/lib/libjavascriptcoregtk-4.0.so.18(+0x9db992) [0x7fd112cb9992]
```

**Comment by dobladov** [comment]
I did all the steps, removing the second definition of [multilib] definitely fixes the repositories but I get the same error.

![screenshot from 2018-04-27 13-43-54](https://user-images.githubusercontent.com/1938043/39365579-0ffc6552-4a21-11e8-9ba4-ce2ca588754c.png)

![screenshot from 2018-04-27 13-42-40](https://user-images.githubusercontent.com/1938043/39365534-e60f16a4-4a20-11e8-9e37-97c1b7291e91.png)


![screenshot from 2018-04-27 13-41-38](https://user-images.githubusercontent.com/1938043/39365481-c1b46dfe-4a20-11e8-90de-f05c5ebb19b0.png)

**Comment by dobladov** [comment]
I just was able to fix the problem doing both, the solution mentioned here and this [unable-to-install-cannot-create-download-package-list-metalinks](https://forum.antergos.com/post/70846)

**Comment by Noxbru** [comment]
Hi,

First thing, the original issue is different from the one being discussed, please open a new one for this cases. I know that the 'metalinks' error is quite common, but the underlying problem is different.

Second. The fix in the previous comment is somehow valid but probably crashes when installing mate. The correct one should be this:

Edit the file /usr/share/cnchi/src/download/metalink.py and delete 'cinnamon' from the list at line 340.
Edit the file /usr/share/cnchi/src/pacman/pac.py and delete 'cinnamon' from the list at line 269.

**Comment by colps1010** [comment]
Hi, 
I follow the resolution steps and get the same error, but I check the new error with Libreoffice package. I try again without select the Libreoffice package and works fine...

**Comment by killajoe** [comment]
@karasu  this can be closed, as it is solved ?
