### ISSUE TITLE
Installer still fails

### ISSUE THREAD

**Issue by neomerx** [Antergos/Cnchi#879]
### Problem:

![image](https://user-images.githubusercontent.com/10420662/39396761-1699d700-4afd-11e8-9c69-9814a49d37f0.png)

### Steps To Reproduce:
1. git clone the repo, switch to 0.14.x branch with `git clone https://github.com/Antergos/Cnchi cnchi && cd cnchi && git checkout 0.14.x`
2. replace default cnchi with `cd .. && sudo rm -rf /usr/share/cnchi && sudo mv cnchi/ /usr/share/`
3. run the installer

### Log Files
```
2018-04-28 12:54:41 [DEBUG] install.py(495) install_packages(): Installing packages...
2018-04-28 12:54:41 [ERROR] process.py(130) run(): 'NoneType' object is not subscriptable
2018-04-28 12:54:41 [ERROR] process.py(135) run(): Traceback (most recent call last):
2018-04-28 12:54:41 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 108, in run
    self.pkg.packages, self.down.metalinks)
2018-04-28 12:54:41 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/pages/automatic.py", line 367, in run_install
    self.installation.start()
2018-04-28 12:54:41 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/misc/extra.py", line 191, in helper
    return func(*args, **kwargs)
2018-04-28 12:54:41 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/install.py", line 329, in start
    self.install_packages()
2018-04-28 12:54:41 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/install.py", line 499, in install_packages
    pkgs=self.packages, conflicts=None, options=None)
2018-04-28 12:54:41 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/pacman/pac.py", line 276, in install
    one_repo_pkgs = {pkg for one_repo_group in one_repo_groups
2018-04-28 12:54:41 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/pacman/pac.py", line 277, in <setcomp>
    for pkg in one_repo_group[1] if one_repo_group}
2018-04-28 12:54:41 [ERROR] process.py(135) run(): TypeError: 'NoneType' object is not subscriptable
2018-04-28 12:54:41 [INFO] slides.py(276) manage_events_from_cb_queue(): Fetching libgcrypt 1.8.2-1 (858/861)...
2018-04-28 12:54:41 [INFO] slides.py(276) manage_events_from_cb_queue(): Fetching libnl 3.4.0-1 (859/861)...
2018-04-28 12:54:41 [INFO] slides.py(276) manage_events_from_cb_queue(): Fetching wireless-regdb 2017.03.07-1 (860/861)...
2018-04-28 12:54:41 [INFO] slides.py(276) manage_events_from_cb_queue(): Fetching crda 3.18-1 (861/861)...
2018-04-28 12:54:41 [DEBUG] connectionpool.py(208) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2018-04-28 12:54:41 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=0&result=False HTTP/1.1" 301 None
2018-04-28 12:54:41 [DEBUG] connectionpool.py(396) _make_request(): http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=0&result=False HTTP/1.1" 502 None
2018-04-28 12:54:41 [ERROR] logging_utils.py(212) send_install_result(): Can't send install result. An exception of type JSONDecodeError occured. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
```

PS http://build.antergos.com seems down

**Comment by karasu** [comment]
Please, try version 0.14.426

And yes, we know that the build server is down... thanks for warning us, though!

**Comment by neomerx** [comment]
Seems to work. Thoud I'd keep it open for some time so people can see how to make work until new release.

![image](https://user-images.githubusercontent.com/10420662/39397301-c3a47114-4b05-11e8-9fe9-eb60a8244a75.png)
